/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * ShowDoc 导出接口 OpenAPI
 * 根据 ShowDoc 原始页面自动生成的 OpenAPI 3.0 规范。
 * OpenAPI spec version: 1.0.0
 */
import type { GetQuestcenterBusinessModelEwsModelEwsNodeList200ChildNodesItem } from './getQuestcenterBusinessModelEwsModelEwsNodeList200ChildNodesItem'
import type { GetQuestcenterBusinessModelEwsModelEwsNodeList200ElementsItem } from './getQuestcenterBusinessModelEwsModelEwsNodeList200ElementsItem'
import type { GetQuestcenterBusinessModelEwsModelEwsNodeList200ParentNodesItem } from './getQuestcenterBusinessModelEwsModelEwsNodeList200ParentNodesItem'

export type GetQuestcenterBusinessModelEwsModelEwsNodeList200 = {
  node_id: string
  node_name: string
  code: string
  remark: string
  is_array: boolean
  required: boolean
  has_parent_node: boolean
  parent_nodes: GetQuestcenterBusinessModelEwsModelEwsNodeList200ParentNodesItem[]
  has_child_node: boolean
  child_nodes: GetQuestcenterBusinessModelEwsModelEwsNodeList200ChildNodesItem[]
  has_element: boolean
  elements: GetQuestcenterBusinessModelEwsModelEwsNodeList200ElementsItem[]
}
