/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * ShowDoc 导出接口 OpenAPI
 * 根据 ShowDoc 原始页面自动生成的 OpenAPI 3.0 规范。
 * OpenAPI spec version: 1.0.0
 */
import type { GetQuestcenterBusinessModelHighRiskSettingGetNodeList200ItemElementsItem } from './getQuestcenterBusinessModelHighRiskSettingGetNodeList200ItemElementsItem'

export type GetQuestcenterBusinessModelHighRiskSettingGetNodeList200Item = {
  node_id: string
  node_name: string
  code: string
  has_parent_node: boolean
  has_child_node: boolean
  has_element: boolean
  elements: GetQuestcenterBusinessModelHighRiskSettingGetNodeList200ItemElementsItem[]
  required: boolean
  is_array: boolean
  min_limit_str: string
  max_limit_str: string
}
