/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * ShowDoc 导出接口 OpenAPI
 * 根据 ShowDoc 原始页面自动生成的 OpenAPI 3.0 规范。
 * OpenAPI spec version: 1.0.0
 */
import type { GetQuestcenterInformedTemplateGetTemplateList200ListItem } from './getQuestcenterInformedTemplateGetTemplateList200ListItem'

export type GetQuestcenterInformedTemplateGetTemplateList200 = {
  pages: number
  total: number
  list: GetQuestcenterInformedTemplateGetTemplateList200ListItem[]
  page_size: number
  page_num: number
}
