/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * ShowDoc 导出接口 OpenAPI
 * 根据 ShowDoc 原始页面自动生成的 OpenAPI 3.0 规范。
 * OpenAPI spec version: 1.0.0
 */

export type GetQuestcenterBusinessModelEwsModelListParams = {
  /**
   * 分类
   */
  category: number
  /**
   * 发布状态 ```json { "status": "000", "data": [ { "id": "776327234830074523", "unique_id": "776327234830074523", "policy_id": "1", "model_id": "1", "subject_id": "1", "level_group_id": "1", "category": 2, "name": "产科危急值-生化指标", "short_name": "SHZB", "publish_time": "2023-06-20 00:00:00", "publish_status": 2, "enabled_status": 1, "is_standard": 1, "version": 1, "sort": 1, "desc": "预警模型" } ], "request_id": "469900767740776757" } ```
   */
  publish_status: number
}
