/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * ShowDoc 导出接口 OpenAPI
 * 根据 ShowDoc 原始页面自动生成的 OpenAPI 3.0 规范。
 * OpenAPI spec version: 1.0.0
 */

export type GetQuestcenterBusinessModelEwsModelPreview200LevelsItem = {
  id: string
  unique_id: string
  policy_id: string
  group_id: string
  level: number
  name: string
  color_name: string
  color_hex: string
  enabled_status: number
  curd_permission?: unknown | null
  version: number
  sort: number
  desc: string
  isDel: number
}
