/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * ShowDoc 导出接口 OpenAPI
 * 根据 ShowDoc 原始页面自动生成的 OpenAPI 3.0 规范。
 * OpenAPI spec version: 1.0.0
 */
import type { GetQuestcenterTemplateGetTreeDirList200ItemChildListItemChildListItem } from './getQuestcenterTemplateGetTreeDirList200ItemChildListItemChildListItem'

export type GetQuestcenterTemplateGetTreeDirList200ItemChildListItem = {
  id: string
  rank_name: string
  rank: number
  parent_id: string
  sort: number
  has_child: boolean
  child_list: GetQuestcenterTemplateGetTreeDirList200ItemChildListItemChildListItem[]
}
