/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * ShowDoc 导出接口 OpenAPI
 * 根据 ShowDoc 原始页面自动生成的 OpenAPI 3.0 规范。
 * OpenAPI spec version: 1.0.0
 */
import type { GetQuestcenterBusinessModelEwsConfigFieldList200ItemEnumsItem } from './getQuestcenterBusinessModelEwsConfigFieldList200ItemEnumsItem'
import type { GetQuestcenterBusinessModelEwsConfigFieldList200ItemEnumVoItem } from './getQuestcenterBusinessModelEwsConfigFieldList200ItemEnumVoItem'

export type GetQuestcenterBusinessModelEwsConfigFieldList200Item = {
  name: string
  default_value: string
  enums: GetQuestcenterBusinessModelEwsConfigFieldList200ItemEnumsItem[]
  enumVo: GetQuestcenterBusinessModelEwsConfigFieldList200ItemEnumVoItem[]
}
