/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * ShowDoc 导出接口 OpenAPI
 * 根据 ShowDoc 原始页面自动生成的 OpenAPI 3.0 规范。
 * OpenAPI spec version: 1.0.0
 */
import type { GetQuestcenterBusinessModelEwsModelPreview200IndicatorsItem } from './getQuestcenterBusinessModelEwsModelPreview200IndicatorsItem'
import type { GetQuestcenterBusinessModelEwsModelPreview200LevelsItem } from './getQuestcenterBusinessModelEwsModelPreview200LevelsItem'
import type { GetQuestcenterBusinessModelEwsModelPreview200TriggerConditionsItem } from './getQuestcenterBusinessModelEwsModelPreview200TriggerConditionsItem'

export type GetQuestcenterBusinessModelEwsModelPreview200 = {
  id: string
  unique_id: string
  policy_id: string
  model_id: string
  subject_id: string
  data_group_node_id: string
  level_group_id: string
  category: number
  name: string
  short_name: string
  publish_time: string
  enabled_status: number
  is_standard: number
  curd_permission: number
  version: number
  sort: number
  desc: string
  is_del: number
  indicators: GetQuestcenterBusinessModelEwsModelPreview200IndicatorsItem[]
  trigger_conditions: GetQuestcenterBusinessModelEwsModelPreview200TriggerConditionsItem[]
  levels: GetQuestcenterBusinessModelEwsModelPreview200LevelsItem[]
  is_force: boolean
}
