/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * ShowDoc 导出接口 OpenAPI
 * 根据 ShowDoc 原始页面自动生成的 OpenAPI 3.0 规范。
 * OpenAPI spec version: 1.0.0
 */
import type { GetQuestcenterBusinessModelEwsModelEwsNodeList200Data } from './getQuestcenterBusinessModelEwsModelEwsNodeList200Data'

export type GetQuestcenterBusinessModelEwsModelEwsNodeList200 = {
  status: string
  data: GetQuestcenterBusinessModelEwsModelEwsNodeList200Data
  request_id: string
}
