/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * ShowDoc 导出接口 OpenAPI
 * 根据 ShowDoc 原始页面自动生成的 OpenAPI 3.0 规范。
 * OpenAPI spec version: 1.0.0
 */
import type { GetQuestcenterBusinessModelEwsModelEwsNodeDetail200DataChildNodesItem } from './getQuestcenterBusinessModelEwsModelEwsNodeDetail200DataChildNodesItem'
import type { GetQuestcenterBusinessModelEwsModelEwsNodeDetail200DataElementsItem } from './getQuestcenterBusinessModelEwsModelEwsNodeDetail200DataElementsItem'
import type { GetQuestcenterBusinessModelEwsModelEwsNodeDetail200DataParentNodesItem } from './getQuestcenterBusinessModelEwsModelEwsNodeDetail200DataParentNodesItem'

export type GetQuestcenterBusinessModelEwsModelEwsNodeDetail200Data = {
  node_id: string
  node_name: string
  code: string
  remark: string
  is_array: boolean
  required: boolean
  has_parent_node: boolean
  parent_nodes: GetQuestcenterBusinessModelEwsModelEwsNodeDetail200DataParentNodesItem[]
  has_child_node: boolean
  child_nodes: GetQuestcenterBusinessModelEwsModelEwsNodeDetail200DataChildNodesItem[]
  has_element: boolean
  elements: GetQuestcenterBusinessModelEwsModelEwsNodeDetail200DataElementsItem[]
}
