/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * ShowDoc 导出接口 OpenAPI
 * 根据 ShowDoc 原始页面自动生成的 OpenAPI 3.0 规范。
 * OpenAPI spec version: 1.0.0
 */

export type GetQuestcenterBusinessModelEwsModelList200Item = {
  id: string
  unique_id: string
  policy_id: string
  model_id: string
  subject_id: string
  level_group_id: string
  category: number
  name: string
  short_name: string
  publish_time: string
  publish_status: number
  enabled_status: number
  is_standard: number
  version: number
  sort: number
  desc: string
}
