/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * ShowDoc 导出接口 OpenAPI
 * 根据 ShowDoc 原始页面自动生成的 OpenAPI 3.0 规范。
 * OpenAPI spec version: 1.0.0
 */
import type { GetQuestcenterBusinessModelEwsConfigOperatorTypeList200DataItem } from './getQuestcenterBusinessModelEwsConfigOperatorTypeList200DataItem'

export type GetQuestcenterBusinessModelEwsConfigOperatorTypeList200 = {
  status: string
  data: GetQuestcenterBusinessModelEwsConfigOperatorTypeList200DataItem[]
  request_id: string
}
