/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * ShowDoc 导出接口 OpenAPI
 * 根据 ShowDoc 原始页面自动生成的 OpenAPI 3.0 规范。
 * OpenAPI spec version: 1.0.0
 */
import type { GetQuestcenterTemplateGetTemplateDetailByPaperId200DataSubjectListItemQuestChildrenPaper } from './getQuestcenterTemplateGetTemplateDetailByPaperId200DataSubjectListItemQuestChildrenPaper'
import type { GetQuestcenterTemplateGetTemplateDetailByPaperId200DataSubjectListItemQuestionOptionItem } from './getQuestcenterTemplateGetTemplateDetailByPaperId200DataSubjectListItemQuestionOptionItem'

export type GetQuestcenterTemplateGetTemplateDetailByPaperId200DataSubjectListItem = {
  subject_id: string
  level_flag: number
  sort: number
  question_type: number
  answer_type: number
  question_title: string
  question_option: GetQuestcenterTemplateGetTemplateDetailByPaperId200DataSubjectListItemQuestionOptionItem[]
  required_status: number
  quest_children_paper: GetQuestcenterTemplateGetTemplateDetailByPaperId200DataSubjectListItemQuestChildrenPaper
  judge_score: number
  judge_condition: number
  satisfy_score: number
}
