/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * ShowDoc 导出接口 OpenAPI
 * 根据 ShowDoc 原始页面自动生成的 OpenAPI 3.0 规范。
 * OpenAPI spec version: 1.0.0
 */
import type { GetQuestcenterTemplateGetTemplateDetailByPaperId200ScoreOptionItem } from './getQuestcenterTemplateGetTemplateDetailByPaperId200ScoreOptionItem'
import type { GetQuestcenterTemplateGetTemplateDetailByPaperId200SubjectListItem } from './getQuestcenterTemplateGetTemplateDetailByPaperId200SubjectListItem'

export type GetQuestcenterTemplateGetTemplateDetailByPaperId200 = {
  paper_id: string
  template_id: string
  version: string
  level_flag: number
  status: number
  type_status: number
  title: string
  title_abbr: string
  illustrate: string
  publish_user: string
  publish_time: string
  publish_name: string
  rich_text: string
  inform_status: number
  inform_sign: number
  subject_list: GetQuestcenterTemplateGetTemplateDetailByPaperId200SubjectListItem[]
  score_option: GetQuestcenterTemplateGetTemplateDetailByPaperId200ScoreOptionItem[]
  create_time: string
}
