/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * ShowDoc 导出接口 OpenAPI
 * 根据 ShowDoc 原始页面自动生成的 OpenAPI 3.0 规范。
 * OpenAPI spec version: 1.0.0
 */
import type { GetQuestcenterBusinessModelEwsConfigFieldList200DataItemEnumsItem } from './getQuestcenterBusinessModelEwsConfigFieldList200DataItemEnumsItem'
import type { GetQuestcenterBusinessModelEwsConfigFieldList200DataItemEnumVoItem } from './getQuestcenterBusinessModelEwsConfigFieldList200DataItemEnumVoItem'

export type GetQuestcenterBusinessModelEwsConfigFieldList200DataItem = {
  name: string
  default_value: string
  enums: GetQuestcenterBusinessModelEwsConfigFieldList200DataItemEnumsItem[]
  enumVo: GetQuestcenterBusinessModelEwsConfigFieldList200DataItemEnumVoItem[]
}
