/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * ShowDoc 导出接口 OpenAPI
 * 根据 ShowDoc 原始页面自动生成的 OpenAPI 3.0 规范。
 * OpenAPI spec version: 1.0.0
 */
import type { GetQuestcenterBusinessModelEwsModelEwsNodeList200DataChildNodesItem } from './getQuestcenterBusinessModelEwsModelEwsNodeList200DataChildNodesItem'
import type { GetQuestcenterBusinessModelEwsModelEwsNodeList200DataElementsItem } from './getQuestcenterBusinessModelEwsModelEwsNodeList200DataElementsItem'
import type { GetQuestcenterBusinessModelEwsModelEwsNodeList200DataParentNodesItem } from './getQuestcenterBusinessModelEwsModelEwsNodeList200DataParentNodesItem'

export type GetQuestcenterBusinessModelEwsModelEwsNodeList200Data = {
  node_id: string
  node_name: string
  code: string
  remark: string
  is_array: boolean
  required: boolean
  has_parent_node: boolean
  parent_nodes: GetQuestcenterBusinessModelEwsModelEwsNodeList200DataParentNodesItem[]
  has_child_node: boolean
  child_nodes: GetQuestcenterBusinessModelEwsModelEwsNodeList200DataChildNodesItem[]
  has_element: boolean
  elements: GetQuestcenterBusinessModelEwsModelEwsNodeList200DataElementsItem[]
}
