/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * ShowDoc 导出接口 OpenAPI
 * 根据 ShowDoc 原始页面自动生成的 OpenAPI 3.0 规范。
 * OpenAPI spec version: 1.0.0
 */
import type { GetQuestcenterTemplateGetTreeDirList200DataItemChildListItem } from './getQuestcenterTemplateGetTreeDirList200DataItemChildListItem'

export type GetQuestcenterTemplateGetTreeDirList200DataItem = {
  id: string
  rank_name: string
  rank: number
  sort: number
  has_child: boolean
  child_list: GetQuestcenterTemplateGetTreeDirList200DataItemChildListItem[]
}
