/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * ShowDoc 导出接口 OpenAPI
 * 根据 ShowDoc 原始页面自动生成的 OpenAPI 3.0 规范。
 * OpenAPI spec version: 1.0.0
 */
import type { GetQuestcenterBusinessModelEwsModelPreview200IndicatorsItemExpressionsItemExpressionArgsItem } from './getQuestcenterBusinessModelEwsModelPreview200IndicatorsItemExpressionsItemExpressionArgsItem'

export type GetQuestcenterBusinessModelEwsModelPreview200IndicatorsItemExpressionsItem = {
  id: string
  unique_id: string
  policy_id: string
  indicator_id: string
  level_id: string
  function_id: string
  definition_type: number
  execute_expression: string
  origin_expression: string
  origin_function: string
  version: number
  sort: number
  desc: string
  is_del: number
  expression_args: GetQuestcenterBusinessModelEwsModelPreview200IndicatorsItemExpressionsItemExpressionArgsItem[]
}
