/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * ShowDoc 导出接口 OpenAPI
 * 根据 ShowDoc 原始页面自动生成的 OpenAPI 3.0 规范。
 * OpenAPI spec version: 1.0.0
 */

export type GetQuestcenterMedicalTextTemplateGetTemplateListParams = {
  /**
   * 模版类型 1-个人模版 0/2-科室模版（科室尽量使用0）
   */
  template_type: number
  /**
   * 模版分类 1-主诊断 2-产前检查临床诊断其他
   */
  template_source: number
}
