/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * ShowDoc 导出接口 OpenAPI
 * 根据 ShowDoc 原始页面自动生成的 OpenAPI 3.0 规范。
 * OpenAPI spec version: 1.0.0
 */

export type GetQuestcenterMedicalTemplateFindParagraphCodeListParams = {
  /**
   * 模版ID
   */
  template_id: string
  /**
   * 是否获取全部待添加段落 true-全部 false-不是
   */
  is_all: boolean
  /**
   * 父级段落编码类型，如果没有则传空
   */
  parent_paragraph_code: string
}
