/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * ShowDoc 导出接口 OpenAPI
 * 根据 ShowDoc 原始页面自动生成的 OpenAPI 3.0 规范。
 * OpenAPI spec version: 1.0.0
 */

export type GetQuestcenterBusinessModelEwsModelPageParams = {
  /**
   * 分类
   */
  category: number
  /**
   * 发布状态
   */
  publish_status: number
  /**
   * 页数
   */
  page_num?: number
  /**
   * 页面大小
   */
  page_size?: number
  /**
   * 搜索key ```json ```
   */
  search_key?: string
}
