/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * ShowDoc 导出接口 OpenAPI
 * 根据 ShowDoc 原始页面自动生成的 OpenAPI 3.0 规范。
 * OpenAPI spec version: 1.0.0
 */
import type { Op322PostQuestcenterTemplateCreateTemplateBodySubjectListItemQuestChildrenPaperSubjectListItem } from './op322PostQuestcenterTemplateCreateTemplateBodySubjectListItemQuestChildrenPaperSubjectListItem'

export type Op322PostQuestcenterTemplateCreateTemplateBodySubjectListItemQuestChildrenPaper = {
  paper_id: string
  level_flag: number
  status: number
  subject_list: Op322PostQuestcenterTemplateCreateTemplateBodySubjectListItemQuestChildrenPaperSubjectListItem[]
  create_time: string
}
