/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * ShowDoc 导出接口 OpenAPI
 * 根据 ShowDoc 原始页面自动生成的 OpenAPI 3.0 规范。
 * OpenAPI spec version: 1.0.0
 */
import type { Op321GetQuestcenterTemplateGetTemplateDetail200DataSubjectListItemQuestChildrenPaper } from './op321GetQuestcenterTemplateGetTemplateDetail200DataSubjectListItemQuestChildrenPaper'
import type { Op321GetQuestcenterTemplateGetTemplateDetail200DataSubjectListItemQuestionOptionItem } from './op321GetQuestcenterTemplateGetTemplateDetail200DataSubjectListItemQuestionOptionItem'

export type Op321GetQuestcenterTemplateGetTemplateDetail200DataSubjectListItem = {
  subject_id: string
  level_flag: number
  sort: number
  question_type: number
  answer_type: number
  question_title: string
  question_option: Op321GetQuestcenterTemplateGetTemplateDetail200DataSubjectListItemQuestionOptionItem[]
  required_status: number
  quest_children_paper: Op321GetQuestcenterTemplateGetTemplateDetail200DataSubjectListItemQuestChildrenPaper
  judge_score: number
  judge_condition: number
  satisfy_score: number
}
