/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * ShowDoc 导出接口 OpenAPI
 * 根据 ShowDoc 原始页面自动生成的 OpenAPI 3.0 规范。
 * OpenAPI spec version: 1.0.0
 */

export type Op322PostQuestcenterTemplateCreateTemplateBodyScoreOptionItem = {
  index: string
  choose_status: boolean
  choose_name: string
  choose_type: number
  score: number
  min_score: number
  max_score: number
  min_judge: number
  max_judge: number
}
