/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * ShowDoc 导出接口 OpenAPI
 * 根据 ShowDoc 原始页面自动生成的 OpenAPI 3.0 规范。
 * OpenAPI spec version: 1.0.0
 */
import type { Op327GetQuestcenterTemplateGetTemplateDetailByPaperId200DataScoreOptionItem } from './op327GetQuestcenterTemplateGetTemplateDetailByPaperId200DataScoreOptionItem'
import type { Op327GetQuestcenterTemplateGetTemplateDetailByPaperId200DataSubjectListItem } from './op327GetQuestcenterTemplateGetTemplateDetailByPaperId200DataSubjectListItem'

export type Op327GetQuestcenterTemplateGetTemplateDetailByPaperId200Data = {
  paper_id: string
  template_id: string
  version: string
  level_flag: number
  status: number
  type_status: number
  title: string
  title_abbr: string
  illustrate: string
  publish_user: string
  publish_time: string
  publish_name: string
  rich_text: string
  inform_status: number
  inform_sign: number
  subject_list: Op327GetQuestcenterTemplateGetTemplateDetailByPaperId200DataSubjectListItem[]
  score_option: Op327GetQuestcenterTemplateGetTemplateDetailByPaperId200DataScoreOptionItem[]
  create_time: string
}
