/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * ShowDoc 导出接口 OpenAPI
 * 根据 ShowDoc 原始页面自动生成的 OpenAPI 3.0 规范。
 * OpenAPI spec version: 1.0.0
 */
import type { Op323PostQuestcenterTemplateUpdateTemplateBodyScoreOptionItem } from './op323PostQuestcenterTemplateUpdateTemplateBodyScoreOptionItem'
import type { Op323PostQuestcenterTemplateUpdateTemplateBodySubjectListItem } from './op323PostQuestcenterTemplateUpdateTemplateBodySubjectListItem'

export type Op323PostQuestcenterTemplateUpdateTemplateBody = {
  template_id: string
  level_flag: number
  type_status: number
  title: string
  title_abbr: string
  illustrate: string
  publish_user: string
  publish_time: string
  publish_name: string
  rich_text: string
  inform_status: number
  inform_sign: number
  subject_list: Op323PostQuestcenterTemplateUpdateTemplateBodySubjectListItem[]
  score_option: Op323PostQuestcenterTemplateUpdateTemplateBodyScoreOptionItem[]
  create_time: string
}
