/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * ShowDoc 导出接口 OpenAPI
 * 根据 ShowDoc 原始页面自动生成的 OpenAPI 3.0 规范。
 * OpenAPI spec version: 1.0.0
 */
import type { Op437PostQuestcenterMedicalTemplateUpdateParagraphNodeParamsBodyChildNodesItemElementsItem } from './op437PostQuestcenterMedicalTemplateUpdateParagraphNodeParamsBodyChildNodesItemElementsItem'

export type Op437PostQuestcenterMedicalTemplateUpdateParagraphNodeParamsBodyChildNodesItem = {
  node_id: string
  node_name: string
  code: string
  remark: string
  has_parent_node: boolean
  has_child_node: boolean
  has_element: boolean
  elements: Op437PostQuestcenterMedicalTemplateUpdateParagraphNodeParamsBodyChildNodesItemElementsItem[]
  required: boolean
  is_array: boolean
  max_limit_str: string
  min_limit_str: string
}
