/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * ShowDoc 导出接口 OpenAPI
 * 根据 ShowDoc 原始页面自动生成的 OpenAPI 3.0 规范。
 * OpenAPI spec version: 1.0.0
 */

export type Op430PostQuestcenterMedicalTemplateUpdateTemplateBody = {
  /** 模版编码 */
  template_id: string
  /** 模版名称 */
  template_name: string
  /** 模版备注 */
  remark: string
}
