/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * ShowDoc 导出接口 OpenAPI
 * 根据 ShowDoc 原始页面自动生成的 OpenAPI 3.0 规范。
 * OpenAPI spec version: 1.0.0
 */

export type Op439GetQuestcenterMedicalTemplateGetTemplateListParams = {
  /**
   * 第?页
   */
  page_num?: number
  /**
   * 每页数量
   */
  page_size?: number
  /**
   * 发布状态 0-未发布 1-已发布
   */
  status?: number
  /**
   * 搜索关键词 模版名称
   */
  key?: string
}
