/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * ShowDoc 导出接口 OpenAPI
 * 根据 ShowDoc 原始页面自动生成的 OpenAPI 3.0 规范。
 * OpenAPI spec version: 1.0.0
 */

export type Op442GetQuestcenterMedicalTemplateGetTemplateDetailByMedicalId200DataParagraphListItemChildParagraphListItemNodeListItemChildNodesItemElementsItemWarnListItem =
  {
    warn_id: number
    node_id: number
    element_id: number
    min_value: number
    min_contain: number
    warn_status: number
    warn_color: string
    max_value: number
    max_contain: number
  }
