/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * ShowDoc 导出接口 OpenAPI
 * 根据 ShowDoc 原始页面自动生成的 OpenAPI 3.0 规范。
 * OpenAPI spec version: 1.0.0
 */

export type Op457PostQuestcenterInformedTemplateUpdateTemplateBody = {
  template_id: string
  title: string
  title_abbr: string
  rich_text: string
  medical_id: string
  dept_type: string
  dept_name: string
  use_range: number
  edit_type: number
  sign_type: string
  client_type: string
  doc_type_id: number
}
