/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * ShowDoc 导出接口 OpenAPI
 * 根据 ShowDoc 原始页面自动生成的 OpenAPI 3.0 规范。
 * OpenAPI spec version: 1.0.0
 */

export type Op455GetQuestcenterInformedTemplateGetTemplateListParams = {
  /**
   * 第?页
   */
  page_num?: number
  /**
   * 每页数量
   */
  page_size?: number
  /**
   * 发布状态<br>0-未发布<br>1-已发布
   */
  status?: number
  /**
   * 模版主题
   */
  type_topic?: number
  /**
   * 所属科室 0-全院 对应编码
   */
  dept_type?: string
  /**
   * 使用范围 0-全院 1-住院 2-门诊
   */
  use_range?: number
  /**
   * 客户端列表 1-门诊医生站 2-母胎医学穿刺工作站 3-超声检查室PAD 4-手术室PAD
   */
  client_type?: number
  /**
   * 文档类型ID
   */
  doc_type_id?: number
  /**
   * 搜索关键词
   */
  key?: string
}
