/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * ShowDoc 导出接口 OpenAPI
 * 根据 ShowDoc 原始页面自动生成的 OpenAPI 3.0 规范。
 * OpenAPI spec version: 1.0.0
 */
import type { Op465GetQuestcenterInformedTemplateGetTemplateDetailByMedicalId200Data } from './op465GetQuestcenterInformedTemplateGetTemplateDetailByMedicalId200Data'

export type Op465GetQuestcenterInformedTemplateGetTemplateDetailByMedicalId200 = {
  status: string
  data: Op465GetQuestcenterInformedTemplateGetTemplateDetailByMedicalId200Data
  request_id: string
}
