/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * ShowDoc 导出接口 OpenAPI
 * 根据 ShowDoc 原始页面自动生成的 OpenAPI 3.0 规范。
 * OpenAPI spec version: 1.0.0
 */
import type { Op465GetQuestcenterInformedTemplateGetTemplateDetailByMedicalId200DataParagraphListItem } from './op465GetQuestcenterInformedTemplateGetTemplateDetailByMedicalId200DataParagraphListItem'

export type Op465GetQuestcenterInformedTemplateGetTemplateDetailByMedicalId200Data = {
  medical_id: string
  template_id: string
  version: string
  template_name: string
  status: number
  publish_user: string
  publish_time: string
  publish_name: string
  used: number
  remark: string
  create_time: string
  paragraph_list: Op465GetQuestcenterInformedTemplateGetTemplateDetailByMedicalId200DataParagraphListItem[]
}
