/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * ShowDoc 导出接口 OpenAPI
 * 根据 ShowDoc 原始页面自动生成的 OpenAPI 3.0 规范。
 * OpenAPI spec version: 1.0.0
 */

export type Op510GetQuestcenterMedicalTextTemplateGetTemplatePageParams = {
  /**
   * 模版类型 1-个人模版 2-科室模版
   */
  template_type: number
  /**
   * 模版分类 1-主诊断 2-产前检查临床诊断其他
   */
  template_source: number
  /**
   * 第？页
   */
  page_num: number
  /**
   * 每页数量
   */
  page_size: number
}
