/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * ShowDoc 导出接口 OpenAPI
 * 根据 ShowDoc 原始页面自动生成的 OpenAPI 3.0 规范。
 * OpenAPI spec version: 1.0.0
 */
import type { Op551PostQuestcenterBusinessModelHighRiskSettingUpdateFactorBodyIcd10CodeListItem } from './op551PostQuestcenterBusinessModelHighRiskSettingUpdateFactorBodyIcd10CodeListItem'
import type { Op551PostQuestcenterBusinessModelHighRiskSettingUpdateFactorBodyRiskCodeListItem } from './op551PostQuestcenterBusinessModelHighRiskSettingUpdateFactorBodyRiskCodeListItem'

export type Op551PostQuestcenterBusinessModelHighRiskSettingUpdateFactorBody = {
  factor_id: string
  type_id: string
  value_type: number
  factor_name: string
  judge_type: number
  value_type_unit: string
  bind_element_id: string
  min_limit: string
  max_limit: string
  risk_code_list: Op551PostQuestcenterBusinessModelHighRiskSettingUpdateFactorBodyRiskCodeListItem[]
  icd10_code_list: Op551PostQuestcenterBusinessModelHighRiskSettingUpdateFactorBodyIcd10CodeListItem[]
}
