/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * ShowDoc 导出接口 OpenAPI
 * 根据 ShowDoc 原始页面自动生成的 OpenAPI 3.0 规范。
 * OpenAPI spec version: 1.0.0
 */

export type Op553PostQuestcenterBusinessModelHighRiskUsingCalculateHighRiskBodyHighRiskValue = {
  de02_01_026_00?: string
  de05_01_024_00?: string
  ck_syfs?: string
}
