/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * ShowDoc 导出接口 OpenAPI
 * 根据 ShowDoc 原始页面自动生成的 OpenAPI 3.0 规范。
 * OpenAPI spec version: 1.0.0
 */
import type { Op551PostQuestcenterBusinessModelHighRiskSettingUpdateFactorBodyRiskCodeListItemCompareEnumsItem } from './op551PostQuestcenterBusinessModelHighRiskSettingUpdateFactorBodyRiskCodeListItemCompareEnumsItem'

export type Op551PostQuestcenterBusinessModelHighRiskSettingUpdateFactorBodyRiskCodeListItem = {
  code_id: string
  factor_id: string
  factor_code: string
  factor_hex_color: string
  factor_desc: string
  compare_value: string
  compare_type: number
  compare_rank: number
  compare_enums: Op551PostQuestcenterBusinessModelHighRiskSettingUpdateFactorBodyRiskCodeListItemCompareEnumsItem[]
}
