/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * ShowDoc 导出接口 OpenAPI
 * 根据 ShowDoc 原始页面自动生成的 OpenAPI 3.0 规范。
 * OpenAPI spec version: 1.0.0
 */
import type { Op553PostQuestcenterBusinessModelHighRiskUsingCalculateHighRisk200DataItemRiskCodeListItemCompareEnumsItem } from './op553PostQuestcenterBusinessModelHighRiskUsingCalculateHighRisk200DataItemRiskCodeListItemCompareEnumsItem'

export type Op553PostQuestcenterBusinessModelHighRiskUsingCalculateHighRisk200DataItemRiskCodeListItem =
  {
    code_id: string
    factor_id: string
    factor_code: string
    factor_hex_color: string
    factor_desc: string
    compare_value: string
    compare_type: number
    compare_rank: number
    match_status: boolean
    compare_enums: Op553PostQuestcenterBusinessModelHighRiskUsingCalculateHighRisk200DataItemRiskCodeListItemCompareEnumsItem[]
  }
