/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * ShowDoc 导出接口 OpenAPI
 * 根据 ShowDoc 原始页面自动生成的 OpenAPI 3.0 规范。
 * OpenAPI spec version: 1.0.0
 */
import type { Op553PostQuestcenterBusinessModelHighRiskUsingCalculateHighRiskBodyHighRiskValue } from './op553PostQuestcenterBusinessModelHighRiskUsingCalculateHighRiskBodyHighRiskValue'

export type Op553PostQuestcenterBusinessModelHighRiskUsingCalculateHighRiskBody = {
  group_id: string
  high_risk_value: Op553PostQuestcenterBusinessModelHighRiskUsingCalculateHighRiskBodyHighRiskValue
}
