/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * ShowDoc 导出接口 OpenAPI
 * 根据 ShowDoc 原始页面自动生成的 OpenAPI 3.0 规范。
 * OpenAPI spec version: 1.0.0
 */
import type { Op565PostQuestcenterBusinessModelEwsModelSaveBodyIndicatorGroupsItem } from './op565PostQuestcenterBusinessModelEwsModelSaveBodyIndicatorGroupsItem'
import type { Op565PostQuestcenterBusinessModelEwsModelSaveBodyIndicatorsItem } from './op565PostQuestcenterBusinessModelEwsModelSaveBodyIndicatorsItem'
import type { Op565PostQuestcenterBusinessModelEwsModelSaveBodyTriggerConditionsItem } from './op565PostQuestcenterBusinessModelEwsModelSaveBodyTriggerConditionsItem'

export type Op565PostQuestcenterBusinessModelEwsModelSaveBody = {
  id: number
  data_group_node_id: string
  is_force: boolean
  indicators: Op565PostQuestcenterBusinessModelEwsModelSaveBodyIndicatorsItem[]
  trigger_conditions: Op565PostQuestcenterBusinessModelEwsModelSaveBodyTriggerConditionsItem[]
  indicator_groups: Op565PostQuestcenterBusinessModelEwsModelSaveBodyIndicatorGroupsItem[]
}
