/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * ShowDoc 导出接口 OpenAPI
 * 根据 ShowDoc 原始页面自动生成的 OpenAPI 3.0 规范。
 * OpenAPI spec version: 1.0.0
 */

export type Op569GetQuestcenterBusinessModelEwsModelPreview200IndicatorsItemExpressionsItemExpressionArgsItem =
  {
    id: string
    unique_id: string
    policy_id: string
    expression_id: number
    type: number
    variable_type: number
    origin_name: string
    embed_name: string
    match_rule: number
    version: number
    sort: number
    desc: string
    is_del: number
  }
