/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * ShowDoc 导出接口 OpenAPI
 * 根据 ShowDoc 原始页面自动生成的 OpenAPI 3.0 规范。
 * OpenAPI spec version: 1.0.0
 */

export type Op569GetQuestcenterBusinessModelEwsModelPreview200TriggerConditionsItem = {
  id: string
  unique_id: string
  policy_id: string
  model_id: string
  level_id: string
  ref_id: string
  ref_type: number
  trigger_factory_count: number
  trigger_factory_count_sign: number
  exist_time: string
  exist_time_unit: number
  exist_time_method: number
  version: number
  sort: number
  desc: string
  is_del: number
}
