/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * ShowDoc 导出接口 OpenAPI
 * 根据 ShowDoc 原始页面自动生成的 OpenAPI 3.0 规范。
 * OpenAPI spec version: 1.0.0
 */
import type { Op562GetQuestcenterBusinessModelEwsModelEwsNodeList200DataChildNodesItem } from './op562GetQuestcenterBusinessModelEwsModelEwsNodeList200DataChildNodesItem'
import type { Op562GetQuestcenterBusinessModelEwsModelEwsNodeList200DataElementsItem } from './op562GetQuestcenterBusinessModelEwsModelEwsNodeList200DataElementsItem'
import type { Op562GetQuestcenterBusinessModelEwsModelEwsNodeList200DataParentNodesItem } from './op562GetQuestcenterBusinessModelEwsModelEwsNodeList200DataParentNodesItem'

export type Op562GetQuestcenterBusinessModelEwsModelEwsNodeList200Data = {
  node_id: string
  node_name: string
  code: string
  remark: string
  is_array: boolean
  required: boolean
  has_parent_node: boolean
  parent_nodes: Op562GetQuestcenterBusinessModelEwsModelEwsNodeList200DataParentNodesItem[]
  has_child_node: boolean
  child_nodes: Op562GetQuestcenterBusinessModelEwsModelEwsNodeList200DataChildNodesItem[]
  has_element: boolean
  elements: Op562GetQuestcenterBusinessModelEwsModelEwsNodeList200DataElementsItem[]
}
