/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * ShowDoc 导出接口 OpenAPI
 * 根据 ShowDoc 原始页面自动生成的 OpenAPI 3.0 规范。
 * OpenAPI spec version: 1.0.0
 */
import type { Op569GetQuestcenterBusinessModelEwsModelPreview200IndicatorsItemExpressionsItem } from './op569GetQuestcenterBusinessModelEwsModelPreview200IndicatorsItemExpressionsItem'

export type Op569GetQuestcenterBusinessModelEwsModelPreview200IndicatorsItem = {
  id: string
  unique_id: string
  policy_id: string
  model_id: string
  data_group_node_id: string
  data_element_code: string
  name: string
  unit: string
  enabled_status: number
  version: number
  sort: number
  desc: string
  max: number
  min: number
  expressions: Op569GetQuestcenterBusinessModelEwsModelPreview200IndicatorsItemExpressionsItem[]
}
