/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * ShowDoc 导出接口 OpenAPI
 * 根据 ShowDoc 原始页面自动生成的 OpenAPI 3.0 规范。
 * OpenAPI spec version: 1.0.0
 */
import type { Op579GetQuestcenterBusinessModelEwsConfigFieldList200DataItem } from './op579GetQuestcenterBusinessModelEwsConfigFieldList200DataItem'

export type Op579GetQuestcenterBusinessModelEwsConfigFieldList200 = {
  status: string
  data: Op579GetQuestcenterBusinessModelEwsConfigFieldList200DataItem[]
  request_id: string
}
