/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * ShowDoc 导出接口 OpenAPI
 * 根据 ShowDoc 原始页面自动生成的 OpenAPI 3.0 规范。
 * OpenAPI spec version: 1.0.0
 */

export type Op616PostQuestcenterBusinessModelEwsModelStateBody = {
  /** 预警模型ID */
  id: number
  /** 发布状态 1.发布 2.不发布 ```json ``` */
  publish_status: number
}
