/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * ShowDoc 导出接口 OpenAPI
 * 根据 ShowDoc 原始页面自动生成的 OpenAPI 3.0 规范。
 * OpenAPI spec version: 1.0.0
 */
import type { Op626GetQuestcenterBusinessModelEwsModelEwsNodeDetail200DataChildNodesItem } from './op626GetQuestcenterBusinessModelEwsModelEwsNodeDetail200DataChildNodesItem'
import type { Op626GetQuestcenterBusinessModelEwsModelEwsNodeDetail200DataElementsItem } from './op626GetQuestcenterBusinessModelEwsModelEwsNodeDetail200DataElementsItem'
import type { Op626GetQuestcenterBusinessModelEwsModelEwsNodeDetail200DataParentNodesItem } from './op626GetQuestcenterBusinessModelEwsModelEwsNodeDetail200DataParentNodesItem'

export type Op626GetQuestcenterBusinessModelEwsModelEwsNodeDetail200Data = {
  node_id: string
  node_name: string
  code: string
  remark: string
  is_array: boolean
  required: boolean
  has_parent_node: boolean
  parent_nodes: Op626GetQuestcenterBusinessModelEwsModelEwsNodeDetail200DataParentNodesItem[]
  has_child_node: boolean
  child_nodes: Op626GetQuestcenterBusinessModelEwsModelEwsNodeDetail200DataChildNodesItem[]
  has_element: boolean
  elements: Op626GetQuestcenterBusinessModelEwsModelEwsNodeDetail200DataElementsItem[]
}
