/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * ShowDoc 导出接口 OpenAPI
 * 根据 ShowDoc 原始页面自动生成的 OpenAPI 3.0 规范。
 * OpenAPI spec version: 1.0.0
 */

export type Op626GetQuestcenterBusinessModelEwsModelEwsNodeDetailParams = {
  /**
   * 数据组节点ID
   */
  data_group_node_id?: string
}
