/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * ShowDoc 导出接口 OpenAPI
 * 根据 ShowDoc 原始页面自动生成的 OpenAPI 3.0 规范。
 * OpenAPI spec version: 1.0.0
 */
import type { PostQuestcenterBusinessModelHighRiskUsingCalculateHighRisk200ItemIcd10CodeListItem } from './postQuestcenterBusinessModelHighRiskUsingCalculateHighRisk200ItemIcd10CodeListItem'
import type { PostQuestcenterBusinessModelHighRiskUsingCalculateHighRisk200ItemRiskCodeListItem } from './postQuestcenterBusinessModelHighRiskUsingCalculateHighRisk200ItemRiskCodeListItem'

export type PostQuestcenterBusinessModelHighRiskUsingCalculateHighRisk200Item = {
  factor_id: string
  type_id: string
  type_name: string
  value_type: number
  factor_name: string
  judge_type: number
  value_type_unit: string
  risk_code_list: PostQuestcenterBusinessModelHighRiskUsingCalculateHighRisk200ItemRiskCodeListItem[]
  icd10_code_list: PostQuestcenterBusinessModelHighRiskUsingCalculateHighRisk200ItemIcd10CodeListItem[]
}
