/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * ShowDoc 导出接口 OpenAPI
 * 根据 ShowDoc 原始页面自动生成的 OpenAPI 3.0 规范。
 * OpenAPI spec version: 1.0.0
 */
import type { PostQuestcenterBusinessModelEwsModelSaveBodyIndicatorsItemExpressionsItem } from './postQuestcenterBusinessModelEwsModelSaveBodyIndicatorsItemExpressionsItem'

export type PostQuestcenterBusinessModelEwsModelSaveBodyIndicatorsItem = {
  id: number
  data_element_code: string
  name: string
  sort: string
  persistence_policy: number
  version: number
  max: string
  min: string
  desc: string
  expressions: PostQuestcenterBusinessModelEwsModelSaveBodyIndicatorsItemExpressionsItem[]
}
