/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * ShowDoc 导出接口 OpenAPI
 * 根据 ShowDoc 原始页面自动生成的 OpenAPI 3.0 规范。
 * OpenAPI spec version: 1.0.0
 */
import type { PostQuestcenterBusinessModelEwsModelSaveBodyIndicatorGroupsItem } from './postQuestcenterBusinessModelEwsModelSaveBodyIndicatorGroupsItem'
import type { PostQuestcenterBusinessModelEwsModelSaveBodyIndicatorsItem } from './postQuestcenterBusinessModelEwsModelSaveBodyIndicatorsItem'
import type { PostQuestcenterBusinessModelEwsModelSaveBodyTriggerConditionsItem } from './postQuestcenterBusinessModelEwsModelSaveBodyTriggerConditionsItem'

export type PostQuestcenterBusinessModelEwsModelSaveBody = {
  id: number
  data_group_node_id: string
  is_force: boolean
  indicators: PostQuestcenterBusinessModelEwsModelSaveBodyIndicatorsItem[]
  trigger_conditions: PostQuestcenterBusinessModelEwsModelSaveBodyTriggerConditionsItem[]
  indicator_groups: PostQuestcenterBusinessModelEwsModelSaveBodyIndicatorGroupsItem[]
}
