/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * ShowDoc 导出接口 OpenAPI
 * 根据 ShowDoc 原始页面自动生成的 OpenAPI 3.0 规范。
 * OpenAPI spec version: 1.0.0
 */

export type PostQuestcenterMedicalTemplateUpdateTemplateParagraphModernTextBody = {
  /** 段落ID */
  paragraph_id: string
  /** 可视化类型 1-模版配置 2-定制开发| */
  modern_type: number
  /** 可视化文本 */
  modern_text: string
}
