/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * ShowDoc 导出接口 OpenAPI
 * 根据 ShowDoc 原始页面自动生成的 OpenAPI 3.0 规范。
 * OpenAPI spec version: 1.0.0
 */
import type { PostQuestcenterTemplateCreateTemplateBodyScoreOptionItem } from './postQuestcenterTemplateCreateTemplateBodyScoreOptionItem'
import type { PostQuestcenterTemplateCreateTemplateBodySubjectListItem } from './postQuestcenterTemplateCreateTemplateBodySubjectListItem'

export type PostQuestcenterTemplateCreateTemplateBody = {
  type_status: number
  title: string
  title_abbr: string
  illustrate: string
  concluding_remarks: string
  publish_user: string
  publish_time: string
  publish_name: string
  rich_text: string
  inform_status: number
  inform_sign: number
  subject_list: PostQuestcenterTemplateCreateTemplateBodySubjectListItem[]
  score_option: PostQuestcenterTemplateCreateTemplateBodyScoreOptionItem[]
  create_time: string
}
