/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * ShowDoc 导出接口 OpenAPI
 * 根据 ShowDoc 原始页面自动生成的 OpenAPI 3.0 规范。
 * OpenAPI spec version: 1.0.0
 */
import type { PostQuestcenterTemplateCreateTemplateBodySubjectListItemQuestChildrenPaper } from './postQuestcenterTemplateCreateTemplateBodySubjectListItemQuestChildrenPaper'
import type { PostQuestcenterTemplateCreateTemplateBodySubjectListItemQuestionOptionItem } from './postQuestcenterTemplateCreateTemplateBodySubjectListItemQuestionOptionItem'

export type PostQuestcenterTemplateCreateTemplateBodySubjectListItem = {
  subject_id: string
  level_flag: number
  sort: number
  question_type: number
  answer_type: number
  question_title: string
  question_option: PostQuestcenterTemplateCreateTemplateBodySubjectListItemQuestionOptionItem[]
  required_status: number
  quest_children_paper: PostQuestcenterTemplateCreateTemplateBodySubjectListItemQuestChildrenPaper
  judge_score: number
  judge_condition: number
  satisfy_score: number
  not_satisfy_score: number
}
