/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * ShowDoc 导出接口 OpenAPI
 * 根据 ShowDoc 原始页面自动生成的 OpenAPI 3.0 规范。
 * OpenAPI spec version: 1.0.0
 */

export type PostQuestcenterMedicalTemplateCreateParagraphNodeTreeBodyNodeTreeItemChildListItemChildListItem =
  {
    id: string
    paragraph_code: string
    paragraph_name: string
    rank: number
    parent_paragraph_code: string
    sort: number
    is_choose: boolean
    has_child: boolean
  }
