/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * ShowDoc 导出接口 OpenAPI
 * 根据 ShowDoc 原始页面自动生成的 OpenAPI 3.0 规范。
 * OpenAPI spec version: 1.0.0
 */

export type PostQuestcenterBusinessModelEwsModelSaveBodyTriggerConditionsItem = {
  id: number
  ref_id: number
  ref_type: number
  level: number
  trigger_factory_count: number
  trigger_factory_count_sign: number
  exist_time: number
  exist_time_unit: number
  exist_time_method: number
  desc: string
}
