/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * ShowDoc 导出接口 OpenAPI
 * 根据 ShowDoc 原始页面自动生成的 OpenAPI 3.0 规范。
 * OpenAPI spec version: 1.0.0
 */

import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'
import { useMutation, useQuery } from '@tanstack/react-query'
import type { ErrorType } from '../request'

import { customFetch } from '../request'
import type {
  GetQuestcenterDocumentTemplateTreeGetTreeDirList200Item,
  GetQuestcenterInformedTemplateGetMedicalTemplateList200,
  GetQuestcenterInformedTemplateGetMedicalTemplateListParams,
  GetQuestcenterInformedTemplateGetNextStep200Item,
  GetQuestcenterInformedTemplateGetNextStepParams,
  GetQuestcenterInformedTemplateGetTemplateDetail200,
  GetQuestcenterInformedTemplateGetTemplateDetailByMedicalId200,
  GetQuestcenterInformedTemplateGetTemplateDetailByMedicalIdParams,
  GetQuestcenterInformedTemplateGetTemplateDetailByPaperId200,
  GetQuestcenterInformedTemplateGetTemplateDetailByPaperIdParams,
  GetQuestcenterInformedTemplateGetTemplateDetailParams,
  GetQuestcenterInformedTemplateGetTemplateHistoryList200Item,
  GetQuestcenterInformedTemplateGetTemplateHistoryListParams,
  GetQuestcenterInformedTemplateGetTemplateList200,
  GetQuestcenterInformedTemplateGetTemplateListParams,
  PostQuestcenterAppliedTemplateGetSubjectDept200Item,
  PostQuestcenterAppliedTemplateGetSubjectDeptBody,
  PostQuestcenterInformedTemplateCloseTemplate200,
  PostQuestcenterInformedTemplateCloseTemplateBody,
  PostQuestcenterInformedTemplateCreateTemplate200,
  PostQuestcenterInformedTemplateCreateTemplateBody,
  PostQuestcenterInformedTemplateDeleteTemplate200,
  PostQuestcenterInformedTemplateDeleteTemplateBody,
  PostQuestcenterInformedTemplateGetSubjectDept200Item,
  PostQuestcenterInformedTemplateGetSubjectDeptBody,
  PostQuestcenterInformedTemplatePublishTemplate200,
  PostQuestcenterInformedTemplatePublishTemplateBody,
  PostQuestcenterInformedTemplateUpdateTemplate200,
  PostQuestcenterInformedTemplateUpdateTemplateBody,
  PostQuestcenterRecordTemplateGetSubjectDept200Item,
  PostQuestcenterRecordTemplateGetSubjectDeptBody,
} from './schemas'
export type postQuestcenterAppliedTemplateGetSubjectDeptResponse200 = {
  data: PostQuestcenterAppliedTemplateGetSubjectDept200Item[]
  status: 200
}

export type postQuestcenterAppliedTemplateGetSubjectDeptResponseSuccess =
  postQuestcenterAppliedTemplateGetSubjectDeptResponse200 & {
    headers: Headers
  }

export type postQuestcenterAppliedTemplateGetSubjectDeptResponse =
  postQuestcenterAppliedTemplateGetSubjectDeptResponseSuccess

export const getPostQuestcenterAppliedTemplateGetSubjectDeptUrl = () => {
  return `/questcenter/applied_template/get_subject_dept`
}

/**
 * 接口说明：专科申请单
 * @summary 获取全部学科列表(知情告知、记录单、专科申请单)
 */
export const postQuestcenterAppliedTemplateGetSubjectDept = async (
  postQuestcenterAppliedTemplateGetSubjectDeptBody?: PostQuestcenterAppliedTemplateGetSubjectDeptBody,
  options?: RequestInit
): Promise<postQuestcenterAppliedTemplateGetSubjectDeptResponse> => {
  return customFetch<postQuestcenterAppliedTemplateGetSubjectDeptResponse>(
    getPostQuestcenterAppliedTemplateGetSubjectDeptUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(postQuestcenterAppliedTemplateGetSubjectDeptBody),
    }
  )
}

export const getPostQuestcenterAppliedTemplateGetSubjectDeptMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postQuestcenterAppliedTemplateGetSubjectDept>>,
    TError,
    { data?: PostQuestcenterAppliedTemplateGetSubjectDeptBody },
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof postQuestcenterAppliedTemplateGetSubjectDept>>,
  TError,
  { data?: PostQuestcenterAppliedTemplateGetSubjectDeptBody },
  TContext
> => {
  const mutationKey = ['postQuestcenterAppliedTemplateGetSubjectDept']
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postQuestcenterAppliedTemplateGetSubjectDept>>,
    { data?: PostQuestcenterAppliedTemplateGetSubjectDeptBody }
  > = (props) => {
    const { data } = props ?? {}

    return postQuestcenterAppliedTemplateGetSubjectDept(data)
  }

  return { mutationFn, ...mutationOptions }
}

export type PostQuestcenterAppliedTemplateGetSubjectDeptMutationResult = NonNullable<
  Awaited<ReturnType<typeof postQuestcenterAppliedTemplateGetSubjectDept>>
>
export type PostQuestcenterAppliedTemplateGetSubjectDeptMutationBody =
  | PostQuestcenterAppliedTemplateGetSubjectDeptBody
  | undefined
export type PostQuestcenterAppliedTemplateGetSubjectDeptMutationError = ErrorType<unknown>

/**
 * @summary 获取全部学科列表(知情告知、记录单、专科申请单)
 */
export const usePostQuestcenterAppliedTemplateGetSubjectDept = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postQuestcenterAppliedTemplateGetSubjectDept>>,
      TError,
      { data?: PostQuestcenterAppliedTemplateGetSubjectDeptBody },
      TContext
    >
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof postQuestcenterAppliedTemplateGetSubjectDept>>,
  TError,
  { data?: PostQuestcenterAppliedTemplateGetSubjectDeptBody },
  TContext
> => {
  return useMutation(
    getPostQuestcenterAppliedTemplateGetSubjectDeptMutationOptions(options),
    queryClient
  )
}

export type getQuestcenterDocumentTemplateTreeGetTreeDirListResponse200 = {
  data: GetQuestcenterDocumentTemplateTreeGetTreeDirList200Item[]
  status: 200
}

export type getQuestcenterDocumentTemplateTreeGetTreeDirListResponseSuccess =
  getQuestcenterDocumentTemplateTreeGetTreeDirListResponse200 & {
    headers: Headers
  }

export type getQuestcenterDocumentTemplateTreeGetTreeDirListResponse =
  getQuestcenterDocumentTemplateTreeGetTreeDirListResponseSuccess

export const getGetQuestcenterDocumentTemplateTreeGetTreeDirListUrl = () => {
  return `/questcenter/document_template_tree/get_tree_dir_list`
}

/**
 * 获取文书模版分类树
 * @summary 获取文书模版分类树
 */
export const getQuestcenterDocumentTemplateTreeGetTreeDirList = async (
  options?: RequestInit
): Promise<getQuestcenterDocumentTemplateTreeGetTreeDirListResponse> => {
  return customFetch<getQuestcenterDocumentTemplateTreeGetTreeDirListResponse>(
    getGetQuestcenterDocumentTemplateTreeGetTreeDirListUrl(),
    {
      ...options,
      method: 'GET',
    }
  )
}

export const getGetQuestcenterDocumentTemplateTreeGetTreeDirListQueryKey = () => {
  return [`/questcenter/document_template_tree/get_tree_dir_list`] as const
}

export const getGetQuestcenterDocumentTemplateTreeGetTreeDirListQueryOptions = <
  TData = Awaited<ReturnType<typeof getQuestcenterDocumentTemplateTreeGetTreeDirList>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getQuestcenterDocumentTemplateTreeGetTreeDirList>>,
      TError,
      TData
    >
  >
}) => {
  const { query: queryOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ?? getGetQuestcenterDocumentTemplateTreeGetTreeDirListQueryKey()

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getQuestcenterDocumentTemplateTreeGetTreeDirList>>
  > = ({ signal }) => getQuestcenterDocumentTemplateTreeGetTreeDirList({ signal })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getQuestcenterDocumentTemplateTreeGetTreeDirList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetQuestcenterDocumentTemplateTreeGetTreeDirListQueryResult = NonNullable<
  Awaited<ReturnType<typeof getQuestcenterDocumentTemplateTreeGetTreeDirList>>
>
export type GetQuestcenterDocumentTemplateTreeGetTreeDirListQueryError = ErrorType<unknown>

export function useGetQuestcenterDocumentTemplateTreeGetTreeDirList<
  TData = Awaited<ReturnType<typeof getQuestcenterDocumentTemplateTreeGetTreeDirList>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getQuestcenterDocumentTemplateTreeGetTreeDirList>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getQuestcenterDocumentTemplateTreeGetTreeDirList>>,
          TError,
          Awaited<ReturnType<typeof getQuestcenterDocumentTemplateTreeGetTreeDirList>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetQuestcenterDocumentTemplateTreeGetTreeDirList<
  TData = Awaited<ReturnType<typeof getQuestcenterDocumentTemplateTreeGetTreeDirList>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getQuestcenterDocumentTemplateTreeGetTreeDirList>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getQuestcenterDocumentTemplateTreeGetTreeDirList>>,
          TError,
          Awaited<ReturnType<typeof getQuestcenterDocumentTemplateTreeGetTreeDirList>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetQuestcenterDocumentTemplateTreeGetTreeDirList<
  TData = Awaited<ReturnType<typeof getQuestcenterDocumentTemplateTreeGetTreeDirList>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getQuestcenterDocumentTemplateTreeGetTreeDirList>>,
        TError,
        TData
      >
    >
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 获取文书模版分类树
 */

export function useGetQuestcenterDocumentTemplateTreeGetTreeDirList<
  TData = Awaited<ReturnType<typeof getQuestcenterDocumentTemplateTreeGetTreeDirList>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getQuestcenterDocumentTemplateTreeGetTreeDirList>>,
        TError,
        TData
      >
    >
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetQuestcenterDocumentTemplateTreeGetTreeDirListQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}

export type postQuestcenterInformedTemplateCloseTemplateResponse200 = {
  data: PostQuestcenterInformedTemplateCloseTemplate200
  status: 200
}

export type postQuestcenterInformedTemplateCloseTemplateResponseSuccess =
  postQuestcenterInformedTemplateCloseTemplateResponse200 & {
    headers: Headers
  }

export type postQuestcenterInformedTemplateCloseTemplateResponse =
  postQuestcenterInformedTemplateCloseTemplateResponseSuccess

export const getPostQuestcenterInformedTemplateCloseTemplateUrl = () => {
  return `/questcenter/informed_template/close_template`
}

/**
 * 模版取消发布
 * @summary 模版取消发布
 */
export const postQuestcenterInformedTemplateCloseTemplate = async (
  postQuestcenterInformedTemplateCloseTemplateBody: PostQuestcenterInformedTemplateCloseTemplateBody,
  options?: RequestInit
): Promise<postQuestcenterInformedTemplateCloseTemplateResponse> => {
  return customFetch<postQuestcenterInformedTemplateCloseTemplateResponse>(
    getPostQuestcenterInformedTemplateCloseTemplateUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(postQuestcenterInformedTemplateCloseTemplateBody),
    }
  )
}

export const getPostQuestcenterInformedTemplateCloseTemplateMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postQuestcenterInformedTemplateCloseTemplate>>,
    TError,
    { data: PostQuestcenterInformedTemplateCloseTemplateBody },
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof postQuestcenterInformedTemplateCloseTemplate>>,
  TError,
  { data: PostQuestcenterInformedTemplateCloseTemplateBody },
  TContext
> => {
  const mutationKey = ['postQuestcenterInformedTemplateCloseTemplate']
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postQuestcenterInformedTemplateCloseTemplate>>,
    { data: PostQuestcenterInformedTemplateCloseTemplateBody }
  > = (props) => {
    const { data } = props ?? {}

    return postQuestcenterInformedTemplateCloseTemplate(data)
  }

  return { mutationFn, ...mutationOptions }
}

export type PostQuestcenterInformedTemplateCloseTemplateMutationResult = NonNullable<
  Awaited<ReturnType<typeof postQuestcenterInformedTemplateCloseTemplate>>
>
export type PostQuestcenterInformedTemplateCloseTemplateMutationBody =
  PostQuestcenterInformedTemplateCloseTemplateBody
export type PostQuestcenterInformedTemplateCloseTemplateMutationError = ErrorType<unknown>

/**
 * @summary 模版取消发布
 */
export const usePostQuestcenterInformedTemplateCloseTemplate = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postQuestcenterInformedTemplateCloseTemplate>>,
      TError,
      { data: PostQuestcenterInformedTemplateCloseTemplateBody },
      TContext
    >
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof postQuestcenterInformedTemplateCloseTemplate>>,
  TError,
  { data: PostQuestcenterInformedTemplateCloseTemplateBody },
  TContext
> => {
  return useMutation(
    getPostQuestcenterInformedTemplateCloseTemplateMutationOptions(options),
    queryClient
  )
}

export type postQuestcenterInformedTemplateCreateTemplateResponse200 = {
  data: PostQuestcenterInformedTemplateCreateTemplate200
  status: 200
}

export type postQuestcenterInformedTemplateCreateTemplateResponseSuccess =
  postQuestcenterInformedTemplateCreateTemplateResponse200 & {
    headers: Headers
  }

export type postQuestcenterInformedTemplateCreateTemplateResponse =
  postQuestcenterInformedTemplateCreateTemplateResponseSuccess

export const getPostQuestcenterInformedTemplateCreateTemplateUrl = () => {
  return `/questcenter/informed_template/create_template`
}

/**
 * 添加模版
 * @summary 添加模版
 */
export const postQuestcenterInformedTemplateCreateTemplate = async (
  postQuestcenterInformedTemplateCreateTemplateBody?: PostQuestcenterInformedTemplateCreateTemplateBody,
  options?: RequestInit
): Promise<postQuestcenterInformedTemplateCreateTemplateResponse> => {
  return customFetch<postQuestcenterInformedTemplateCreateTemplateResponse>(
    getPostQuestcenterInformedTemplateCreateTemplateUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(postQuestcenterInformedTemplateCreateTemplateBody),
    }
  )
}

export const getPostQuestcenterInformedTemplateCreateTemplateMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postQuestcenterInformedTemplateCreateTemplate>>,
    TError,
    { data?: PostQuestcenterInformedTemplateCreateTemplateBody },
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof postQuestcenterInformedTemplateCreateTemplate>>,
  TError,
  { data?: PostQuestcenterInformedTemplateCreateTemplateBody },
  TContext
> => {
  const mutationKey = ['postQuestcenterInformedTemplateCreateTemplate']
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postQuestcenterInformedTemplateCreateTemplate>>,
    { data?: PostQuestcenterInformedTemplateCreateTemplateBody }
  > = (props) => {
    const { data } = props ?? {}

    return postQuestcenterInformedTemplateCreateTemplate(data)
  }

  return { mutationFn, ...mutationOptions }
}

export type PostQuestcenterInformedTemplateCreateTemplateMutationResult = NonNullable<
  Awaited<ReturnType<typeof postQuestcenterInformedTemplateCreateTemplate>>
>
export type PostQuestcenterInformedTemplateCreateTemplateMutationBody =
  | PostQuestcenterInformedTemplateCreateTemplateBody
  | undefined
export type PostQuestcenterInformedTemplateCreateTemplateMutationError = ErrorType<unknown>

/**
 * @summary 添加模版
 */
export const usePostQuestcenterInformedTemplateCreateTemplate = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postQuestcenterInformedTemplateCreateTemplate>>,
      TError,
      { data?: PostQuestcenterInformedTemplateCreateTemplateBody },
      TContext
    >
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof postQuestcenterInformedTemplateCreateTemplate>>,
  TError,
  { data?: PostQuestcenterInformedTemplateCreateTemplateBody },
  TContext
> => {
  return useMutation(
    getPostQuestcenterInformedTemplateCreateTemplateMutationOptions(options),
    queryClient
  )
}

export type postQuestcenterInformedTemplateDeleteTemplateResponse200 = {
  data: PostQuestcenterInformedTemplateDeleteTemplate200
  status: 200
}

export type postQuestcenterInformedTemplateDeleteTemplateResponseSuccess =
  postQuestcenterInformedTemplateDeleteTemplateResponse200 & {
    headers: Headers
  }

export type postQuestcenterInformedTemplateDeleteTemplateResponse =
  postQuestcenterInformedTemplateDeleteTemplateResponseSuccess

export const getPostQuestcenterInformedTemplateDeleteTemplateUrl = () => {
  return `/questcenter/informed_template/delete_template`
}

/**
 * 删除模版，只针对，未发布可编辑模版
 * @summary 删除模版，只针对，未发布可编辑模版
 */
export const postQuestcenterInformedTemplateDeleteTemplate = async (
  postQuestcenterInformedTemplateDeleteTemplateBody: PostQuestcenterInformedTemplateDeleteTemplateBody,
  options?: RequestInit
): Promise<postQuestcenterInformedTemplateDeleteTemplateResponse> => {
  return customFetch<postQuestcenterInformedTemplateDeleteTemplateResponse>(
    getPostQuestcenterInformedTemplateDeleteTemplateUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(postQuestcenterInformedTemplateDeleteTemplateBody),
    }
  )
}

export const getPostQuestcenterInformedTemplateDeleteTemplateMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postQuestcenterInformedTemplateDeleteTemplate>>,
    TError,
    { data: PostQuestcenterInformedTemplateDeleteTemplateBody },
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof postQuestcenterInformedTemplateDeleteTemplate>>,
  TError,
  { data: PostQuestcenterInformedTemplateDeleteTemplateBody },
  TContext
> => {
  const mutationKey = ['postQuestcenterInformedTemplateDeleteTemplate']
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postQuestcenterInformedTemplateDeleteTemplate>>,
    { data: PostQuestcenterInformedTemplateDeleteTemplateBody }
  > = (props) => {
    const { data } = props ?? {}

    return postQuestcenterInformedTemplateDeleteTemplate(data)
  }

  return { mutationFn, ...mutationOptions }
}

export type PostQuestcenterInformedTemplateDeleteTemplateMutationResult = NonNullable<
  Awaited<ReturnType<typeof postQuestcenterInformedTemplateDeleteTemplate>>
>
export type PostQuestcenterInformedTemplateDeleteTemplateMutationBody =
  PostQuestcenterInformedTemplateDeleteTemplateBody
export type PostQuestcenterInformedTemplateDeleteTemplateMutationError = ErrorType<unknown>

/**
 * @summary 删除模版，只针对，未发布可编辑模版
 */
export const usePostQuestcenterInformedTemplateDeleteTemplate = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postQuestcenterInformedTemplateDeleteTemplate>>,
      TError,
      { data: PostQuestcenterInformedTemplateDeleteTemplateBody },
      TContext
    >
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof postQuestcenterInformedTemplateDeleteTemplate>>,
  TError,
  { data: PostQuestcenterInformedTemplateDeleteTemplateBody },
  TContext
> => {
  return useMutation(
    getPostQuestcenterInformedTemplateDeleteTemplateMutationOptions(options),
    queryClient
  )
}

export type getQuestcenterInformedTemplateGetMedicalTemplateListResponse200 = {
  data: GetQuestcenterInformedTemplateGetMedicalTemplateList200
  status: 200
}

export type getQuestcenterInformedTemplateGetMedicalTemplateListResponseSuccess =
  getQuestcenterInformedTemplateGetMedicalTemplateListResponse200 & {
    headers: Headers
  }

export type getQuestcenterInformedTemplateGetMedicalTemplateListResponse =
  getQuestcenterInformedTemplateGetMedicalTemplateListResponseSuccess

export const getGetQuestcenterInformedTemplateGetMedicalTemplateListUrl = (
  params?: GetQuestcenterInformedTemplateGetMedicalTemplateListParams
) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/questcenter/informed_template/get_medical_template_list?${stringifiedParams}`
    : `/questcenter/informed_template/get_medical_template_list`
}

/**
 * 获取病历模版列表
 * @summary 获取病历模版列表
 */
export const getQuestcenterInformedTemplateGetMedicalTemplateList = async (
  params?: GetQuestcenterInformedTemplateGetMedicalTemplateListParams,
  options?: RequestInit
): Promise<getQuestcenterInformedTemplateGetMedicalTemplateListResponse> => {
  return customFetch<getQuestcenterInformedTemplateGetMedicalTemplateListResponse>(
    getGetQuestcenterInformedTemplateGetMedicalTemplateListUrl(params),
    {
      ...options,
      method: 'GET',
    }
  )
}

export const getGetQuestcenterInformedTemplateGetMedicalTemplateListQueryKey = (
  params?: GetQuestcenterInformedTemplateGetMedicalTemplateListParams
) => {
  return [
    `/questcenter/informed_template/get_medical_template_list`,
    ...(params ? [params] : []),
  ] as const
}

export const getGetQuestcenterInformedTemplateGetMedicalTemplateListQueryOptions = <
  TData = Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetMedicalTemplateList>>,
  TError = ErrorType<unknown>,
>(
  params?: GetQuestcenterInformedTemplateGetMedicalTemplateListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetMedicalTemplateList>>,
        TError,
        TData
      >
    >
  }
) => {
  const { query: queryOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ??
    getGetQuestcenterInformedTemplateGetMedicalTemplateListQueryKey(params)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetMedicalTemplateList>>
  > = ({ signal }) => getQuestcenterInformedTemplateGetMedicalTemplateList(params, { signal })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetMedicalTemplateList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetQuestcenterInformedTemplateGetMedicalTemplateListQueryResult = NonNullable<
  Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetMedicalTemplateList>>
>
export type GetQuestcenterInformedTemplateGetMedicalTemplateListQueryError = ErrorType<unknown>

export function useGetQuestcenterInformedTemplateGetMedicalTemplateList<
  TData = Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetMedicalTemplateList>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | GetQuestcenterInformedTemplateGetMedicalTemplateListParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetMedicalTemplateList>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetMedicalTemplateList>>,
          TError,
          Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetMedicalTemplateList>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetQuestcenterInformedTemplateGetMedicalTemplateList<
  TData = Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetMedicalTemplateList>>,
  TError = ErrorType<unknown>,
>(
  params?: GetQuestcenterInformedTemplateGetMedicalTemplateListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetMedicalTemplateList>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetMedicalTemplateList>>,
          TError,
          Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetMedicalTemplateList>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetQuestcenterInformedTemplateGetMedicalTemplateList<
  TData = Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetMedicalTemplateList>>,
  TError = ErrorType<unknown>,
>(
  params?: GetQuestcenterInformedTemplateGetMedicalTemplateListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetMedicalTemplateList>>,
        TError,
        TData
      >
    >
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 获取病历模版列表
 */

export function useGetQuestcenterInformedTemplateGetMedicalTemplateList<
  TData = Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetMedicalTemplateList>>,
  TError = ErrorType<unknown>,
>(
  params?: GetQuestcenterInformedTemplateGetMedicalTemplateListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetMedicalTemplateList>>,
        TError,
        TData
      >
    >
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetQuestcenterInformedTemplateGetMedicalTemplateListQueryOptions(
    params,
    options
  )

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}

export type getQuestcenterInformedTemplateGetNextStepResponse200 = {
  data: GetQuestcenterInformedTemplateGetNextStep200Item[]
  status: 200
}

export type getQuestcenterInformedTemplateGetNextStepResponseSuccess =
  getQuestcenterInformedTemplateGetNextStepResponse200 & {
    headers: Headers
  }

export type getQuestcenterInformedTemplateGetNextStepResponse =
  getQuestcenterInformedTemplateGetNextStepResponseSuccess

export const getGetQuestcenterInformedTemplateGetNextStepUrl = (
  params: GetQuestcenterInformedTemplateGetNextStepParams
) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/questcenter/informed_template/get_next_step?${stringifiedParams}`
    : `/questcenter/informed_template/get_next_step`
}

/**
 * 获取下一步步骤的按钮
 * @summary 获取下一步步骤的按钮
 */
export const getQuestcenterInformedTemplateGetNextStep = async (
  params: GetQuestcenterInformedTemplateGetNextStepParams,
  options?: RequestInit
): Promise<getQuestcenterInformedTemplateGetNextStepResponse> => {
  return customFetch<getQuestcenterInformedTemplateGetNextStepResponse>(
    getGetQuestcenterInformedTemplateGetNextStepUrl(params),
    {
      ...options,
      method: 'GET',
    }
  )
}

export const getGetQuestcenterInformedTemplateGetNextStepQueryKey = (
  params?: GetQuestcenterInformedTemplateGetNextStepParams
) => {
  return [`/questcenter/informed_template/get_next_step`, ...(params ? [params] : [])] as const
}

export const getGetQuestcenterInformedTemplateGetNextStepQueryOptions = <
  TData = Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetNextStep>>,
  TError = ErrorType<unknown>,
>(
  params: GetQuestcenterInformedTemplateGetNextStepParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetNextStep>>,
        TError,
        TData
      >
    >
  }
) => {
  const { query: queryOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ?? getGetQuestcenterInformedTemplateGetNextStepQueryKey(params)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetNextStep>>
  > = ({ signal }) => getQuestcenterInformedTemplateGetNextStep(params, { signal })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetNextStep>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetQuestcenterInformedTemplateGetNextStepQueryResult = NonNullable<
  Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetNextStep>>
>
export type GetQuestcenterInformedTemplateGetNextStepQueryError = ErrorType<unknown>

export function useGetQuestcenterInformedTemplateGetNextStep<
  TData = Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetNextStep>>,
  TError = ErrorType<unknown>,
>(
  params: GetQuestcenterInformedTemplateGetNextStepParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetNextStep>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetNextStep>>,
          TError,
          Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetNextStep>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetQuestcenterInformedTemplateGetNextStep<
  TData = Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetNextStep>>,
  TError = ErrorType<unknown>,
>(
  params: GetQuestcenterInformedTemplateGetNextStepParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetNextStep>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetNextStep>>,
          TError,
          Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetNextStep>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetQuestcenterInformedTemplateGetNextStep<
  TData = Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetNextStep>>,
  TError = ErrorType<unknown>,
>(
  params: GetQuestcenterInformedTemplateGetNextStepParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetNextStep>>,
        TError,
        TData
      >
    >
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 获取下一步步骤的按钮
 */

export function useGetQuestcenterInformedTemplateGetNextStep<
  TData = Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetNextStep>>,
  TError = ErrorType<unknown>,
>(
  params: GetQuestcenterInformedTemplateGetNextStepParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetNextStep>>,
        TError,
        TData
      >
    >
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetQuestcenterInformedTemplateGetNextStepQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}

export type postQuestcenterInformedTemplateGetSubjectDeptResponse200 = {
  data: PostQuestcenterInformedTemplateGetSubjectDept200Item[]
  status: 200
}

export type postQuestcenterInformedTemplateGetSubjectDeptResponseSuccess =
  postQuestcenterInformedTemplateGetSubjectDeptResponse200 & {
    headers: Headers
  }

export type postQuestcenterInformedTemplateGetSubjectDeptResponse =
  postQuestcenterInformedTemplateGetSubjectDeptResponseSuccess

export const getPostQuestcenterInformedTemplateGetSubjectDeptUrl = () => {
  return `/questcenter/informed_template/get_subject_dept`
}

/**
 * 接口说明：知情告知
 * @summary 获取全部学科列表(知情告知、记录单、专科申请单)
 */
export const postQuestcenterInformedTemplateGetSubjectDept = async (
  postQuestcenterInformedTemplateGetSubjectDeptBody?: PostQuestcenterInformedTemplateGetSubjectDeptBody,
  options?: RequestInit
): Promise<postQuestcenterInformedTemplateGetSubjectDeptResponse> => {
  return customFetch<postQuestcenterInformedTemplateGetSubjectDeptResponse>(
    getPostQuestcenterInformedTemplateGetSubjectDeptUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(postQuestcenterInformedTemplateGetSubjectDeptBody),
    }
  )
}

export const getPostQuestcenterInformedTemplateGetSubjectDeptMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postQuestcenterInformedTemplateGetSubjectDept>>,
    TError,
    { data?: PostQuestcenterInformedTemplateGetSubjectDeptBody },
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof postQuestcenterInformedTemplateGetSubjectDept>>,
  TError,
  { data?: PostQuestcenterInformedTemplateGetSubjectDeptBody },
  TContext
> => {
  const mutationKey = ['postQuestcenterInformedTemplateGetSubjectDept']
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postQuestcenterInformedTemplateGetSubjectDept>>,
    { data?: PostQuestcenterInformedTemplateGetSubjectDeptBody }
  > = (props) => {
    const { data } = props ?? {}

    return postQuestcenterInformedTemplateGetSubjectDept(data)
  }

  return { mutationFn, ...mutationOptions }
}

export type PostQuestcenterInformedTemplateGetSubjectDeptMutationResult = NonNullable<
  Awaited<ReturnType<typeof postQuestcenterInformedTemplateGetSubjectDept>>
>
export type PostQuestcenterInformedTemplateGetSubjectDeptMutationBody =
  | PostQuestcenterInformedTemplateGetSubjectDeptBody
  | undefined
export type PostQuestcenterInformedTemplateGetSubjectDeptMutationError = ErrorType<unknown>

/**
 * @summary 获取全部学科列表(知情告知、记录单、专科申请单)
 */
export const usePostQuestcenterInformedTemplateGetSubjectDept = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postQuestcenterInformedTemplateGetSubjectDept>>,
      TError,
      { data?: PostQuestcenterInformedTemplateGetSubjectDeptBody },
      TContext
    >
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof postQuestcenterInformedTemplateGetSubjectDept>>,
  TError,
  { data?: PostQuestcenterInformedTemplateGetSubjectDeptBody },
  TContext
> => {
  return useMutation(
    getPostQuestcenterInformedTemplateGetSubjectDeptMutationOptions(options),
    queryClient
  )
}

export type getQuestcenterInformedTemplateGetTemplateDetailResponse200 = {
  data: GetQuestcenterInformedTemplateGetTemplateDetail200
  status: 200
}

export type getQuestcenterInformedTemplateGetTemplateDetailResponseSuccess =
  getQuestcenterInformedTemplateGetTemplateDetailResponse200 & {
    headers: Headers
  }

export type getQuestcenterInformedTemplateGetTemplateDetailResponse =
  getQuestcenterInformedTemplateGetTemplateDetailResponseSuccess

export const getGetQuestcenterInformedTemplateGetTemplateDetailUrl = (
  params: GetQuestcenterInformedTemplateGetTemplateDetailParams
) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/questcenter/informed_template/get_template_detail?${stringifiedParams}`
    : `/questcenter/informed_template/get_template_detail`
}

/**
 * 查询模版详情
 * @summary 查询模版详情
 */
export const getQuestcenterInformedTemplateGetTemplateDetail = async (
  params: GetQuestcenterInformedTemplateGetTemplateDetailParams,
  options?: RequestInit
): Promise<getQuestcenterInformedTemplateGetTemplateDetailResponse> => {
  return customFetch<getQuestcenterInformedTemplateGetTemplateDetailResponse>(
    getGetQuestcenterInformedTemplateGetTemplateDetailUrl(params),
    {
      ...options,
      method: 'GET',
    }
  )
}

export const getGetQuestcenterInformedTemplateGetTemplateDetailQueryKey = (
  params?: GetQuestcenterInformedTemplateGetTemplateDetailParams
) => {
  return [
    `/questcenter/informed_template/get_template_detail`,
    ...(params ? [params] : []),
  ] as const
}

export const getGetQuestcenterInformedTemplateGetTemplateDetailQueryOptions = <
  TData = Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetTemplateDetail>>,
  TError = ErrorType<unknown>,
>(
  params: GetQuestcenterInformedTemplateGetTemplateDetailParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetTemplateDetail>>,
        TError,
        TData
      >
    >
  }
) => {
  const { query: queryOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ?? getGetQuestcenterInformedTemplateGetTemplateDetailQueryKey(params)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetTemplateDetail>>
  > = ({ signal }) => getQuestcenterInformedTemplateGetTemplateDetail(params, { signal })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetTemplateDetail>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetQuestcenterInformedTemplateGetTemplateDetailQueryResult = NonNullable<
  Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetTemplateDetail>>
>
export type GetQuestcenterInformedTemplateGetTemplateDetailQueryError = ErrorType<unknown>

export function useGetQuestcenterInformedTemplateGetTemplateDetail<
  TData = Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetTemplateDetail>>,
  TError = ErrorType<unknown>,
>(
  params: GetQuestcenterInformedTemplateGetTemplateDetailParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetTemplateDetail>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetTemplateDetail>>,
          TError,
          Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetTemplateDetail>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetQuestcenterInformedTemplateGetTemplateDetail<
  TData = Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetTemplateDetail>>,
  TError = ErrorType<unknown>,
>(
  params: GetQuestcenterInformedTemplateGetTemplateDetailParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetTemplateDetail>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetTemplateDetail>>,
          TError,
          Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetTemplateDetail>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetQuestcenterInformedTemplateGetTemplateDetail<
  TData = Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetTemplateDetail>>,
  TError = ErrorType<unknown>,
>(
  params: GetQuestcenterInformedTemplateGetTemplateDetailParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetTemplateDetail>>,
        TError,
        TData
      >
    >
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 查询模版详情
 */

export function useGetQuestcenterInformedTemplateGetTemplateDetail<
  TData = Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetTemplateDetail>>,
  TError = ErrorType<unknown>,
>(
  params: GetQuestcenterInformedTemplateGetTemplateDetailParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetTemplateDetail>>,
        TError,
        TData
      >
    >
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetQuestcenterInformedTemplateGetTemplateDetailQueryOptions(
    params,
    options
  )

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}

export type getQuestcenterInformedTemplateGetTemplateDetailByMedicalIdResponse200 = {
  data: GetQuestcenterInformedTemplateGetTemplateDetailByMedicalId200
  status: 200
}

export type getQuestcenterInformedTemplateGetTemplateDetailByMedicalIdResponseSuccess =
  getQuestcenterInformedTemplateGetTemplateDetailByMedicalIdResponse200 & {
    headers: Headers
  }

export type getQuestcenterInformedTemplateGetTemplateDetailByMedicalIdResponse =
  getQuestcenterInformedTemplateGetTemplateDetailByMedicalIdResponseSuccess

export const getGetQuestcenterInformedTemplateGetTemplateDetailByMedicalIdUrl = (
  params: GetQuestcenterInformedTemplateGetTemplateDetailByMedicalIdParams
) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/questcenter/informed_template/get_template_detail_by_medical_id?${stringifiedParams}`
    : `/questcenter/informed_template/get_template_detail_by_medical_id`
}

/**
 * 获取病历模版详情，medical_id
 * @summary 获取病历模版详情，medical_id
 */
export const getQuestcenterInformedTemplateGetTemplateDetailByMedicalId = async (
  params: GetQuestcenterInformedTemplateGetTemplateDetailByMedicalIdParams,
  options?: RequestInit
): Promise<getQuestcenterInformedTemplateGetTemplateDetailByMedicalIdResponse> => {
  return customFetch<getQuestcenterInformedTemplateGetTemplateDetailByMedicalIdResponse>(
    getGetQuestcenterInformedTemplateGetTemplateDetailByMedicalIdUrl(params),
    {
      ...options,
      method: 'GET',
    }
  )
}

export const getGetQuestcenterInformedTemplateGetTemplateDetailByMedicalIdQueryKey = (
  params?: GetQuestcenterInformedTemplateGetTemplateDetailByMedicalIdParams
) => {
  return [
    `/questcenter/informed_template/get_template_detail_by_medical_id`,
    ...(params ? [params] : []),
  ] as const
}

export const getGetQuestcenterInformedTemplateGetTemplateDetailByMedicalIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetTemplateDetailByMedicalId>>,
  TError = ErrorType<unknown>,
>(
  params: GetQuestcenterInformedTemplateGetTemplateDetailByMedicalIdParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetTemplateDetailByMedicalId>>,
        TError,
        TData
      >
    >
  }
) => {
  const { query: queryOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ??
    getGetQuestcenterInformedTemplateGetTemplateDetailByMedicalIdQueryKey(params)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetTemplateDetailByMedicalId>>
  > = ({ signal }) => getQuestcenterInformedTemplateGetTemplateDetailByMedicalId(params, { signal })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetTemplateDetailByMedicalId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetQuestcenterInformedTemplateGetTemplateDetailByMedicalIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetTemplateDetailByMedicalId>>
>
export type GetQuestcenterInformedTemplateGetTemplateDetailByMedicalIdQueryError =
  ErrorType<unknown>

export function useGetQuestcenterInformedTemplateGetTemplateDetailByMedicalId<
  TData = Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetTemplateDetailByMedicalId>>,
  TError = ErrorType<unknown>,
>(
  params: GetQuestcenterInformedTemplateGetTemplateDetailByMedicalIdParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetTemplateDetailByMedicalId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetTemplateDetailByMedicalId>>,
          TError,
          Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetTemplateDetailByMedicalId>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetQuestcenterInformedTemplateGetTemplateDetailByMedicalId<
  TData = Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetTemplateDetailByMedicalId>>,
  TError = ErrorType<unknown>,
>(
  params: GetQuestcenterInformedTemplateGetTemplateDetailByMedicalIdParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetTemplateDetailByMedicalId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetTemplateDetailByMedicalId>>,
          TError,
          Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetTemplateDetailByMedicalId>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetQuestcenterInformedTemplateGetTemplateDetailByMedicalId<
  TData = Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetTemplateDetailByMedicalId>>,
  TError = ErrorType<unknown>,
>(
  params: GetQuestcenterInformedTemplateGetTemplateDetailByMedicalIdParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetTemplateDetailByMedicalId>>,
        TError,
        TData
      >
    >
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 获取病历模版详情，medical_id
 */

export function useGetQuestcenterInformedTemplateGetTemplateDetailByMedicalId<
  TData = Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetTemplateDetailByMedicalId>>,
  TError = ErrorType<unknown>,
>(
  params: GetQuestcenterInformedTemplateGetTemplateDetailByMedicalIdParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetTemplateDetailByMedicalId>>,
        TError,
        TData
      >
    >
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetQuestcenterInformedTemplateGetTemplateDetailByMedicalIdQueryOptions(
    params,
    options
  )

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}

export type getQuestcenterInformedTemplateGetTemplateDetailByPaperIdResponse200 = {
  data: GetQuestcenterInformedTemplateGetTemplateDetailByPaperId200
  status: 200
}

export type getQuestcenterInformedTemplateGetTemplateDetailByPaperIdResponseSuccess =
  getQuestcenterInformedTemplateGetTemplateDetailByPaperIdResponse200 & {
    headers: Headers
  }

export type getQuestcenterInformedTemplateGetTemplateDetailByPaperIdResponse =
  getQuestcenterInformedTemplateGetTemplateDetailByPaperIdResponseSuccess

export const getGetQuestcenterInformedTemplateGetTemplateDetailByPaperIdUrl = (
  params: GetQuestcenterInformedTemplateGetTemplateDetailByPaperIdParams
) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/questcenter/informed_template/get_template_detail_by_paper_id?${stringifiedParams}`
    : `/questcenter/informed_template/get_template_detail_by_paper_id`
}

/**
 * 查询模版详情根据paper_id
 * @summary 查询模版详情根据paper_id
 */
export const getQuestcenterInformedTemplateGetTemplateDetailByPaperId = async (
  params: GetQuestcenterInformedTemplateGetTemplateDetailByPaperIdParams,
  options?: RequestInit
): Promise<getQuestcenterInformedTemplateGetTemplateDetailByPaperIdResponse> => {
  return customFetch<getQuestcenterInformedTemplateGetTemplateDetailByPaperIdResponse>(
    getGetQuestcenterInformedTemplateGetTemplateDetailByPaperIdUrl(params),
    {
      ...options,
      method: 'GET',
    }
  )
}

export const getGetQuestcenterInformedTemplateGetTemplateDetailByPaperIdQueryKey = (
  params?: GetQuestcenterInformedTemplateGetTemplateDetailByPaperIdParams
) => {
  return [
    `/questcenter/informed_template/get_template_detail_by_paper_id`,
    ...(params ? [params] : []),
  ] as const
}

export const getGetQuestcenterInformedTemplateGetTemplateDetailByPaperIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetTemplateDetailByPaperId>>,
  TError = ErrorType<unknown>,
>(
  params: GetQuestcenterInformedTemplateGetTemplateDetailByPaperIdParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetTemplateDetailByPaperId>>,
        TError,
        TData
      >
    >
  }
) => {
  const { query: queryOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ??
    getGetQuestcenterInformedTemplateGetTemplateDetailByPaperIdQueryKey(params)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetTemplateDetailByPaperId>>
  > = ({ signal }) => getQuestcenterInformedTemplateGetTemplateDetailByPaperId(params, { signal })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetTemplateDetailByPaperId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetQuestcenterInformedTemplateGetTemplateDetailByPaperIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetTemplateDetailByPaperId>>
>
export type GetQuestcenterInformedTemplateGetTemplateDetailByPaperIdQueryError = ErrorType<unknown>

export function useGetQuestcenterInformedTemplateGetTemplateDetailByPaperId<
  TData = Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetTemplateDetailByPaperId>>,
  TError = ErrorType<unknown>,
>(
  params: GetQuestcenterInformedTemplateGetTemplateDetailByPaperIdParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetTemplateDetailByPaperId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetTemplateDetailByPaperId>>,
          TError,
          Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetTemplateDetailByPaperId>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetQuestcenterInformedTemplateGetTemplateDetailByPaperId<
  TData = Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetTemplateDetailByPaperId>>,
  TError = ErrorType<unknown>,
>(
  params: GetQuestcenterInformedTemplateGetTemplateDetailByPaperIdParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetTemplateDetailByPaperId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetTemplateDetailByPaperId>>,
          TError,
          Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetTemplateDetailByPaperId>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetQuestcenterInformedTemplateGetTemplateDetailByPaperId<
  TData = Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetTemplateDetailByPaperId>>,
  TError = ErrorType<unknown>,
>(
  params: GetQuestcenterInformedTemplateGetTemplateDetailByPaperIdParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetTemplateDetailByPaperId>>,
        TError,
        TData
      >
    >
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 查询模版详情根据paper_id
 */

export function useGetQuestcenterInformedTemplateGetTemplateDetailByPaperId<
  TData = Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetTemplateDetailByPaperId>>,
  TError = ErrorType<unknown>,
>(
  params: GetQuestcenterInformedTemplateGetTemplateDetailByPaperIdParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetTemplateDetailByPaperId>>,
        TError,
        TData
      >
    >
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetQuestcenterInformedTemplateGetTemplateDetailByPaperIdQueryOptions(
    params,
    options
  )

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}

export type getQuestcenterInformedTemplateGetTemplateHistoryListResponse200 = {
  data: GetQuestcenterInformedTemplateGetTemplateHistoryList200Item[]
  status: 200
}

export type getQuestcenterInformedTemplateGetTemplateHistoryListResponseSuccess =
  getQuestcenterInformedTemplateGetTemplateHistoryListResponse200 & {
    headers: Headers
  }

export type getQuestcenterInformedTemplateGetTemplateHistoryListResponse =
  getQuestcenterInformedTemplateGetTemplateHistoryListResponseSuccess

export const getGetQuestcenterInformedTemplateGetTemplateHistoryListUrl = (
  params: GetQuestcenterInformedTemplateGetTemplateHistoryListParams
) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/questcenter/informed_template/get_template_history_list?${stringifiedParams}`
    : `/questcenter/informed_template/get_template_history_list`
}

/**
 * 获取历史模版列
 * @summary 获取历史模版列
 */
export const getQuestcenterInformedTemplateGetTemplateHistoryList = async (
  params: GetQuestcenterInformedTemplateGetTemplateHistoryListParams,
  options?: RequestInit
): Promise<getQuestcenterInformedTemplateGetTemplateHistoryListResponse> => {
  return customFetch<getQuestcenterInformedTemplateGetTemplateHistoryListResponse>(
    getGetQuestcenterInformedTemplateGetTemplateHistoryListUrl(params),
    {
      ...options,
      method: 'GET',
    }
  )
}

export const getGetQuestcenterInformedTemplateGetTemplateHistoryListQueryKey = (
  params?: GetQuestcenterInformedTemplateGetTemplateHistoryListParams
) => {
  return [
    `/questcenter/informed_template/get_template_history_list`,
    ...(params ? [params] : []),
  ] as const
}

export const getGetQuestcenterInformedTemplateGetTemplateHistoryListQueryOptions = <
  TData = Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetTemplateHistoryList>>,
  TError = ErrorType<unknown>,
>(
  params: GetQuestcenterInformedTemplateGetTemplateHistoryListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetTemplateHistoryList>>,
        TError,
        TData
      >
    >
  }
) => {
  const { query: queryOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ??
    getGetQuestcenterInformedTemplateGetTemplateHistoryListQueryKey(params)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetTemplateHistoryList>>
  > = ({ signal }) => getQuestcenterInformedTemplateGetTemplateHistoryList(params, { signal })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetTemplateHistoryList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetQuestcenterInformedTemplateGetTemplateHistoryListQueryResult = NonNullable<
  Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetTemplateHistoryList>>
>
export type GetQuestcenterInformedTemplateGetTemplateHistoryListQueryError = ErrorType<unknown>

export function useGetQuestcenterInformedTemplateGetTemplateHistoryList<
  TData = Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetTemplateHistoryList>>,
  TError = ErrorType<unknown>,
>(
  params: GetQuestcenterInformedTemplateGetTemplateHistoryListParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetTemplateHistoryList>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetTemplateHistoryList>>,
          TError,
          Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetTemplateHistoryList>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetQuestcenterInformedTemplateGetTemplateHistoryList<
  TData = Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetTemplateHistoryList>>,
  TError = ErrorType<unknown>,
>(
  params: GetQuestcenterInformedTemplateGetTemplateHistoryListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetTemplateHistoryList>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetTemplateHistoryList>>,
          TError,
          Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetTemplateHistoryList>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetQuestcenterInformedTemplateGetTemplateHistoryList<
  TData = Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetTemplateHistoryList>>,
  TError = ErrorType<unknown>,
>(
  params: GetQuestcenterInformedTemplateGetTemplateHistoryListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetTemplateHistoryList>>,
        TError,
        TData
      >
    >
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 获取历史模版列
 */

export function useGetQuestcenterInformedTemplateGetTemplateHistoryList<
  TData = Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetTemplateHistoryList>>,
  TError = ErrorType<unknown>,
>(
  params: GetQuestcenterInformedTemplateGetTemplateHistoryListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetTemplateHistoryList>>,
        TError,
        TData
      >
    >
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetQuestcenterInformedTemplateGetTemplateHistoryListQueryOptions(
    params,
    options
  )

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}

export type getQuestcenterInformedTemplateGetTemplateListResponse200 = {
  data: GetQuestcenterInformedTemplateGetTemplateList200
  status: 200
}

export type getQuestcenterInformedTemplateGetTemplateListResponseSuccess =
  getQuestcenterInformedTemplateGetTemplateListResponse200 & {
    headers: Headers
  }

export type getQuestcenterInformedTemplateGetTemplateListResponse =
  getQuestcenterInformedTemplateGetTemplateListResponseSuccess

export const getGetQuestcenterInformedTemplateGetTemplateListUrl = (
  params: GetQuestcenterInformedTemplateGetTemplateListParams
) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/questcenter/informed_template/get_template_list?${stringifiedParams}`
    : `/questcenter/informed_template/get_template_list`
}

/**
 * 获取最新模版列表
 * @summary 获取最新模版列表
 */
export const getQuestcenterInformedTemplateGetTemplateList = async (
  params: GetQuestcenterInformedTemplateGetTemplateListParams,
  options?: RequestInit
): Promise<getQuestcenterInformedTemplateGetTemplateListResponse> => {
  return customFetch<getQuestcenterInformedTemplateGetTemplateListResponse>(
    getGetQuestcenterInformedTemplateGetTemplateListUrl(params),
    {
      ...options,
      method: 'GET',
    }
  )
}

export const getGetQuestcenterInformedTemplateGetTemplateListQueryKey = (
  params?: GetQuestcenterInformedTemplateGetTemplateListParams
) => {
  return [`/questcenter/informed_template/get_template_list`, ...(params ? [params] : [])] as const
}

export const getGetQuestcenterInformedTemplateGetTemplateListQueryOptions = <
  TData = Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetTemplateList>>,
  TError = ErrorType<unknown>,
>(
  params: GetQuestcenterInformedTemplateGetTemplateListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetTemplateList>>,
        TError,
        TData
      >
    >
  }
) => {
  const { query: queryOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ?? getGetQuestcenterInformedTemplateGetTemplateListQueryKey(params)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetTemplateList>>
  > = ({ signal }) => getQuestcenterInformedTemplateGetTemplateList(params, { signal })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetTemplateList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetQuestcenterInformedTemplateGetTemplateListQueryResult = NonNullable<
  Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetTemplateList>>
>
export type GetQuestcenterInformedTemplateGetTemplateListQueryError = ErrorType<unknown>

export function useGetQuestcenterInformedTemplateGetTemplateList<
  TData = Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetTemplateList>>,
  TError = ErrorType<unknown>,
>(
  params: GetQuestcenterInformedTemplateGetTemplateListParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetTemplateList>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetTemplateList>>,
          TError,
          Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetTemplateList>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetQuestcenterInformedTemplateGetTemplateList<
  TData = Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetTemplateList>>,
  TError = ErrorType<unknown>,
>(
  params: GetQuestcenterInformedTemplateGetTemplateListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetTemplateList>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetTemplateList>>,
          TError,
          Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetTemplateList>>
        >,
        'initialData'
      >
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetQuestcenterInformedTemplateGetTemplateList<
  TData = Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetTemplateList>>,
  TError = ErrorType<unknown>,
>(
  params: GetQuestcenterInformedTemplateGetTemplateListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetTemplateList>>,
        TError,
        TData
      >
    >
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 获取最新模版列表
 */

export function useGetQuestcenterInformedTemplateGetTemplateList<
  TData = Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetTemplateList>>,
  TError = ErrorType<unknown>,
>(
  params: GetQuestcenterInformedTemplateGetTemplateListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getQuestcenterInformedTemplateGetTemplateList>>,
        TError,
        TData
      >
    >
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetQuestcenterInformedTemplateGetTemplateListQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}

export type postQuestcenterInformedTemplatePublishTemplateResponse200 = {
  data: PostQuestcenterInformedTemplatePublishTemplate200
  status: 200
}

export type postQuestcenterInformedTemplatePublishTemplateResponseSuccess =
  postQuestcenterInformedTemplatePublishTemplateResponse200 & {
    headers: Headers
  }

export type postQuestcenterInformedTemplatePublishTemplateResponse =
  postQuestcenterInformedTemplatePublishTemplateResponseSuccess

export const getPostQuestcenterInformedTemplatePublishTemplateUrl = () => {
  return `/questcenter/informed_template/publish_template`
}

/**
 * 模版发布
 * @summary 模版发布
 */
export const postQuestcenterInformedTemplatePublishTemplate = async (
  postQuestcenterInformedTemplatePublishTemplateBody: PostQuestcenterInformedTemplatePublishTemplateBody,
  options?: RequestInit
): Promise<postQuestcenterInformedTemplatePublishTemplateResponse> => {
  return customFetch<postQuestcenterInformedTemplatePublishTemplateResponse>(
    getPostQuestcenterInformedTemplatePublishTemplateUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(postQuestcenterInformedTemplatePublishTemplateBody),
    }
  )
}

export const getPostQuestcenterInformedTemplatePublishTemplateMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postQuestcenterInformedTemplatePublishTemplate>>,
    TError,
    { data: PostQuestcenterInformedTemplatePublishTemplateBody },
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof postQuestcenterInformedTemplatePublishTemplate>>,
  TError,
  { data: PostQuestcenterInformedTemplatePublishTemplateBody },
  TContext
> => {
  const mutationKey = ['postQuestcenterInformedTemplatePublishTemplate']
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postQuestcenterInformedTemplatePublishTemplate>>,
    { data: PostQuestcenterInformedTemplatePublishTemplateBody }
  > = (props) => {
    const { data } = props ?? {}

    return postQuestcenterInformedTemplatePublishTemplate(data)
  }

  return { mutationFn, ...mutationOptions }
}

export type PostQuestcenterInformedTemplatePublishTemplateMutationResult = NonNullable<
  Awaited<ReturnType<typeof postQuestcenterInformedTemplatePublishTemplate>>
>
export type PostQuestcenterInformedTemplatePublishTemplateMutationBody =
  PostQuestcenterInformedTemplatePublishTemplateBody
export type PostQuestcenterInformedTemplatePublishTemplateMutationError = ErrorType<unknown>

/**
 * @summary 模版发布
 */
export const usePostQuestcenterInformedTemplatePublishTemplate = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postQuestcenterInformedTemplatePublishTemplate>>,
      TError,
      { data: PostQuestcenterInformedTemplatePublishTemplateBody },
      TContext
    >
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof postQuestcenterInformedTemplatePublishTemplate>>,
  TError,
  { data: PostQuestcenterInformedTemplatePublishTemplateBody },
  TContext
> => {
  return useMutation(
    getPostQuestcenterInformedTemplatePublishTemplateMutationOptions(options),
    queryClient
  )
}

export type postQuestcenterInformedTemplateUpdateTemplateResponse200 = {
  data: PostQuestcenterInformedTemplateUpdateTemplate200
  status: 200
}

export type postQuestcenterInformedTemplateUpdateTemplateResponseSuccess =
  postQuestcenterInformedTemplateUpdateTemplateResponse200 & {
    headers: Headers
  }

export type postQuestcenterInformedTemplateUpdateTemplateResponse =
  postQuestcenterInformedTemplateUpdateTemplateResponseSuccess

export const getPostQuestcenterInformedTemplateUpdateTemplateUrl = () => {
  return `/questcenter/informed_template/update_template`
}

/**
 * 更新模版
 * @summary 更新模版
 */
export const postQuestcenterInformedTemplateUpdateTemplate = async (
  postQuestcenterInformedTemplateUpdateTemplateBody?: PostQuestcenterInformedTemplateUpdateTemplateBody,
  options?: RequestInit
): Promise<postQuestcenterInformedTemplateUpdateTemplateResponse> => {
  return customFetch<postQuestcenterInformedTemplateUpdateTemplateResponse>(
    getPostQuestcenterInformedTemplateUpdateTemplateUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(postQuestcenterInformedTemplateUpdateTemplateBody),
    }
  )
}

export const getPostQuestcenterInformedTemplateUpdateTemplateMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postQuestcenterInformedTemplateUpdateTemplate>>,
    TError,
    { data?: PostQuestcenterInformedTemplateUpdateTemplateBody },
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof postQuestcenterInformedTemplateUpdateTemplate>>,
  TError,
  { data?: PostQuestcenterInformedTemplateUpdateTemplateBody },
  TContext
> => {
  const mutationKey = ['postQuestcenterInformedTemplateUpdateTemplate']
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postQuestcenterInformedTemplateUpdateTemplate>>,
    { data?: PostQuestcenterInformedTemplateUpdateTemplateBody }
  > = (props) => {
    const { data } = props ?? {}

    return postQuestcenterInformedTemplateUpdateTemplate(data)
  }

  return { mutationFn, ...mutationOptions }
}

export type PostQuestcenterInformedTemplateUpdateTemplateMutationResult = NonNullable<
  Awaited<ReturnType<typeof postQuestcenterInformedTemplateUpdateTemplate>>
>
export type PostQuestcenterInformedTemplateUpdateTemplateMutationBody =
  | PostQuestcenterInformedTemplateUpdateTemplateBody
  | undefined
export type PostQuestcenterInformedTemplateUpdateTemplateMutationError = ErrorType<unknown>

/**
 * @summary 更新模版
 */
export const usePostQuestcenterInformedTemplateUpdateTemplate = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postQuestcenterInformedTemplateUpdateTemplate>>,
      TError,
      { data?: PostQuestcenterInformedTemplateUpdateTemplateBody },
      TContext
    >
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof postQuestcenterInformedTemplateUpdateTemplate>>,
  TError,
  { data?: PostQuestcenterInformedTemplateUpdateTemplateBody },
  TContext
> => {
  return useMutation(
    getPostQuestcenterInformedTemplateUpdateTemplateMutationOptions(options),
    queryClient
  )
}

export type postQuestcenterRecordTemplateGetSubjectDeptResponse200 = {
  data: PostQuestcenterRecordTemplateGetSubjectDept200Item[]
  status: 200
}

export type postQuestcenterRecordTemplateGetSubjectDeptResponseSuccess =
  postQuestcenterRecordTemplateGetSubjectDeptResponse200 & {
    headers: Headers
  }

export type postQuestcenterRecordTemplateGetSubjectDeptResponse =
  postQuestcenterRecordTemplateGetSubjectDeptResponseSuccess

export const getPostQuestcenterRecordTemplateGetSubjectDeptUrl = () => {
  return `/questcenter/record_template/get_subject_dept`
}

/**
 * 接口说明：记录单
 * @summary 获取全部学科列表(知情告知、记录单、专科申请单)
 */
export const postQuestcenterRecordTemplateGetSubjectDept = async (
  postQuestcenterRecordTemplateGetSubjectDeptBody?: PostQuestcenterRecordTemplateGetSubjectDeptBody,
  options?: RequestInit
): Promise<postQuestcenterRecordTemplateGetSubjectDeptResponse> => {
  return customFetch<postQuestcenterRecordTemplateGetSubjectDeptResponse>(
    getPostQuestcenterRecordTemplateGetSubjectDeptUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(postQuestcenterRecordTemplateGetSubjectDeptBody),
    }
  )
}

export const getPostQuestcenterRecordTemplateGetSubjectDeptMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postQuestcenterRecordTemplateGetSubjectDept>>,
    TError,
    { data?: PostQuestcenterRecordTemplateGetSubjectDeptBody },
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof postQuestcenterRecordTemplateGetSubjectDept>>,
  TError,
  { data?: PostQuestcenterRecordTemplateGetSubjectDeptBody },
  TContext
> => {
  const mutationKey = ['postQuestcenterRecordTemplateGetSubjectDept']
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postQuestcenterRecordTemplateGetSubjectDept>>,
    { data?: PostQuestcenterRecordTemplateGetSubjectDeptBody }
  > = (props) => {
    const { data } = props ?? {}

    return postQuestcenterRecordTemplateGetSubjectDept(data)
  }

  return { mutationFn, ...mutationOptions }
}

export type PostQuestcenterRecordTemplateGetSubjectDeptMutationResult = NonNullable<
  Awaited<ReturnType<typeof postQuestcenterRecordTemplateGetSubjectDept>>
>
export type PostQuestcenterRecordTemplateGetSubjectDeptMutationBody =
  | PostQuestcenterRecordTemplateGetSubjectDeptBody
  | undefined
export type PostQuestcenterRecordTemplateGetSubjectDeptMutationError = ErrorType<unknown>

/**
 * @summary 获取全部学科列表(知情告知、记录单、专科申请单)
 */
export const usePostQuestcenterRecordTemplateGetSubjectDept = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postQuestcenterRecordTemplateGetSubjectDept>>,
      TError,
      { data?: PostQuestcenterRecordTemplateGetSubjectDeptBody },
      TContext
    >
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof postQuestcenterRecordTemplateGetSubjectDept>>,
  TError,
  { data?: PostQuestcenterRecordTemplateGetSubjectDeptBody },
  TContext
> => {
  return useMutation(
    getPostQuestcenterRecordTemplateGetSubjectDeptMutationOptions(options),
    queryClient
  )
}
